### ISSUE TITLE
Math support

### ISSUE THREAD

**Issue by raheems** [MunifTanjim/minimo#100]
Is math support currently available? 

My LaTeX codes are not rendering. I've found in another theme, where math works, the following code in `layouts/partials/footer.html` 

Could you please provide some clue on how to adapt the code for this theme?

```
   <!-- LaTeX math rendering -->
    {{ if or .Params.math .Site.Params.math }}
    <script type="text/x-mathjax-config">
        MathJax.Hub.Config({ tex2jax: { inlineMath: [['$','$'], ['\\(','\\)']] } });
    </script>
    {{ if not .Site.Params.disable_sri }}
    {{ printf "<script src=\"https://cdnjs.cloudflare.com/ajax/libs/mathjax/%s/MathJax.js?config=TeX-AMS_CHTML\" integrity=\"%s\" crossorigin=\"anonymous\"></script>" $js.mathJax.version $js.mathJax.sri | safeHTML }}
    {{ else }}
    <script async src="//cdnjs.cloudflare.com/ajax/libs/mathjax/{{- $js.mathJax.version -}}/MathJax.js?config=TeX-AMS_CHTML"></script>
    {{ end }}
    {{ end }}
```

**Comment by MunifTanjim** [comment]
Try adding

```golang
<script type="text/x-mathjax-config">
    MathJax.Hub.Config({ tex2jax: { inlineMath: [['$','$'], ['\\(','\\)']] } });
</script>
```

after the `MathJax.js` file is included. i.e.

```golang
<!-- LaTeX math rendering -->
{{ if or .Params.math .Site.Params.math }}
  {{ if not .Site.Params.disable_sri }}
    {{ printf "<script src=\"https://cdnjs.cloudflare.com/ajax/libs/mathjax/%s/MathJax.js?config=TeX-AMS_CHTML\" integrity=\"%s\" crossorigin=\"anonymous\"></script>" $js.mathJax.version $js.mathJax.sri | safeHTML }}
  {{ else }}
    <script async src="//cdnjs.cloudflare.com/ajax/libs/mathjax/{{- $js.mathJax.version -}}/MathJax.js?config=TeX-AMS_CHTML"></script>
  {{ end }}
  <script type="text/x-mathjax-config">
    MathJax.Hub.Config({ tex2jax: { inlineMath: [['$','$'], ['\\(','\\)']] } });
  </script>
{{ end }}
```

**Comment by MunifTanjim** [comment]
In which theme did you find the mentioned snippet?

**Comment by raheems** [comment]
OK, thanks :)

Keeping the link  below for other potential users of your theme.

hugo-academic `https://themes.gohugo.io/academic/`

**Comment by raheems** [comment]
If you can also support syntax highlighting for the R language, that would be great. A lot of people from statistics background uses Rmarkdown with blogdown R package using hugo.

**Comment by MunifTanjim** [comment]
Nothing I can do about that. Hugo uses [Chroma](https://github.com/alecthomas/chroma) for syntax highlighting. You can open an issue there if you want.

**Comment by raheems** [comment]
Not a problem. Thanks. I saw it supports R but in the context of merely showing and highlighting R codes. Not in the context of Rmarkdown which processes and prints the outcomes. 

Thanks for your support. This is not something urgent. I can live without syntax highlighting for R with this theme. But somehow the academic theme supports it.

Here are the two links:

Without highlighting:
[https://www.deeplearnr.com/post/2015-07-23-r-rmarkdown/](https://www.deeplearnr.com/post/2015-07-23-r-rmarkdown/)

With highlighting:
[http://eraheem.netlify.com/post/2015-07-23-r-rmarkdown/](http://eraheem.netlify.com/post/2015-07-23-r-rmarkdown/)

**Comment by MunifTanjim** [comment]
Found the problem. Hugo doesn't support `Rmd` markdown format. So it can't highlight `R` codeblocks with Chroma.

The solution is to use a frontend syntax highlighter.

Add this in the `footer.html`:

```
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/default.min.css">
<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/languages/r.min.js"></script>
<script>hljs.initHighlightingOnLoad();</script>
```

This should help.

@raheems

**Comment by raheems** [comment]
That's awesome! It works!! 

Thank you!

**Comment by MunifTanjim** [comment]
@raheems I just pushed MathJax support for Minimo :smiley: 

Take a look: [MathJax Support](https://minimo.netlify.com/docs/mathjax-support/)

**Comment by raheems** [comment]
This is awesome! For me the theme is now complete in terms of functionality :)
I really appreciate it :+1:

**Comment by rgr19** [comment]
Hi! Matjax is broken again, do You know some workaround?

**Comment by MunifTanjim** [comment]
@rgr19 Please open new issue with detailed information. Thanks.

**Comment by rgr19** [comment]
Hi! Look here please! Myself I'm 90% noob in hugo, so do not even know what I'm seeing in shortcode there :(

https://minimo.netlify.com/docs/mathjax-support/

**Comment by MunifTanjim** [comment]
@rgr19 should be fixed now
