### ISSUE TITLE
Cover image and sidebar

### ISSUE THREAD

**Issue by Fastidious** [MunifTanjim/minimo#101]
With the adding of a sidebar, cover images look kind of odd, especially when used with full, and wide styles.

**Comment by MunifTanjim** [comment]
Any suggestions or ideas? @Fastidious

**Comment by Fastidious** [comment]
I have been thinking, @MunifTanjim. It isn't an easy fix, other than letting users know the caveat or, if there is an entry with an image wide, or full, suppressing the sidebar on entry view mode (make it full page, automatically). Not sure how viable is that with Hugo, and/or if would be worth the effort.

**Comment by MunifTanjim** [comment]
That's a good idea. I though of the exact same thing while I was designing the sidebar. But forgot about it later. :sweat_smile:
