### ISSUE TITLE
Sidebar stickiness

### ISSUE THREAD

**Issue by Fastidious** [MunifTanjim/minimo#102]
If the sidebar is set to `sticky: false`, and there are lots of tags being used (like it is my case), and the page being view is short, the scrolling becomes awkward (only half of the web browser page scrolls). On a related topic, if `sticky: true`, and lots of tags, a scrolling bar shows in between the sidebar and main portion.

I can set a default install with all my content to show, if needed.

**Comment by MunifTanjim** [comment]
**About the situation when `sticky: true`:**

It can actually be improved. Take a look at this theme: [Twenty Fifteen](https://twentyfifteendemo.wordpress.com/). See what is happening while you scroll? This behavior can be implemented and remove the scrollbar.

**About the situation when `sticky: false`:**

> the scrolling becomes awkward (only half of the web browser page scrolls)

I don't think I understood what you're saying. What do you mean by it?

**Comment by Fastidious** [comment]
@MunifTanjim it is all broken, but see https://quark.quark.business/test/, scroll. Try the "About" (longer page). That is what I meant on `sticky: false`. Let me know, so I will delete the site.

**Comment by MunifTanjim** [comment]
I see. That's not so good. :confused:

I'll fix it as soon as I can. Thanks for reporting...

**Comment by MunifTanjim** [comment]
@Fastidious, would you please check if the bug (when `sticky: false` is set) is fixed?

**Comment by Fastidious** [comment]
@MunifTanjim will do as soon as I get home. 🤞🏻

**Comment by Fastidious** [comment]
@MunifTanjim it looks much better. The only problem is, when the sidebar is full of tags, the last tags are too close to the bottom of the window. Perhaps padding the bottom on the sidebar as well?
