### ISSUE TITLE
How can I disable "recent_posts" widget in _index.md 

### ISSUE THREAD

**Issue by lijunhw** [MunifTanjim/minimo#104]
I find if the files structure looks like

```
content
  \- projects
      \- lab1
          \- index.html
      \- lab2
          \- index.html
      - _index.md
```

the page example.com/projects/ will have two empty recent posts like 

```
0001, Jan 01
0001, Jan 01
```

Note lab1/index.html and lab2/index.html are not Markdown files. Not sure if this is the cause. 

One solution will be to have the option to disable "recent_posts" widget because not all index page need that. 

Awesome work, by the way.

**Comment by MunifTanjim** [comment]
You need to provide more information. Can you create a example repository that demonstrates this bug? @lijunhw

**Comment by lijunhw** [comment]
I have created an example repo https://github.com/lijunhw/hugo_test/tree/51f6a857a3ddf8a7eaaefd9889fbda8dc42b93b3 . Check out the page at ```/projects```.

**Comment by MunifTanjim** [comment]
In your example repo:

- `/projects/` is a [Section page](https://gohugo.io/templates/section-templates/). Section page in Hugo shows a list of pages in that section. ( What you see is not the "recent_post" widget. ). So, you can't "disable" it.

- `/content/projects/lab1/index.html` is not a markdown file. And there is not [Front Matter](https://gohugo.io/content-management/front-matter/). So, there's no `date` or `title` associated with it. And so, the list shows only `0001, Jan 01`.

If you only want a simple page ( not a section page ):

- You should use the `/content/page/` directory.

And as I stated above, read the Hugo documentation for [Content Management](https://gohugo.io/content-management/). It'll clear a lot of things for you.

If you need further help about understanding Hugo's Content Management, you can post your problems on [Hugo Discussion forum](https://discourse.gohugo.io/).

I hope, it'll help you to get started with Hugo. :slightly_smiling_face:
