### ISSUE TITLE
RSS feed

### ISSUE THREAD

**Issue by Zilkos** [MunifTanjim/minimo#105]
Hi, it's a feature request for adding RSS feed in this awesome theme.

**Comment by MunifTanjim** [comment]
Isn't RSS feed already available for Hugo? @Zilkos 

Hugo [RSS Template](https://gohugo.io/templates/rss/#readout) documentation...

**Comment by Zilkos** [comment]
Oh sorry, the default RSS setup from Hugo is okay with Minimo theme.

I mean, how can I tweak it to exclude menu pages ? 

Pages like "Doc / Typography / About" from your demo site.

**Comment by MunifTanjim** [comment]
I don't know why you would want to exclude pages from the rss feed.

But if you want to do that, you'll need to override the [default RSS template](https://gohugo.io/templates/rss/#the-embedded-rss-xml) of Hugo.

**Comment by Zilkos** [comment]
Because pages are always on the top of the feed... However they are older than other contents. I don't know why the feed isn't date based by default.

**Comment by MunifTanjim** [comment]
Well, that's an issue for the [gohugoio/hugo](https://github.com/gohugoio/hugo) repository.

As I suggested, you need to override the [default RSS template](https://gohugo.io/templates/rss/#the-embedded-rss-xml) of Hugo.

Related doc: [Override Template Files](https://gohugo.io/themes/customizing/#override-template-files)
