### ISSUE TITLE
Customizable main color

### ISSUE THREAD

**Issue by xypnox** [MunifTanjim/minimo#106]
I would love a feature in which I could customize the main color from config.toml rather than editing the file at `\themes\minimo\src\stylesheets\extras\variables\_colors.scss`

**Comment by MunifTanjim** [comment]
Implemented on 8ce036b721afb5db75e241443f24304e3ab56516.

Should work on every modern browsers.

**Comment by jghauser** [comment]
This does not seem to work. After generating the files with `hugo` my `/public/assets/css/main.809149b6.css` has entries such as `border-bottom-color:#ffcd00;border-bottom-color:var(--color-accent)` in it. The relevant line in my `config.toml` is `accentColor = "#ff6e21"`.

I've just updated my website from a few versions back and had to adjust the settings, so maybe I'm simply doing something wrong. If so, a pointer in the right direction would be appreciated!

**Comment by MunifTanjim** [comment]
@jghauser Without taking a look at your repository, all I can say is:

> After updating Minimo, always check that your site's **`config.toml`** file matches the latest [**`config.toml`** file](https://minimo.netlify.com/docs/config-file) format.
>
> A good idea is to double check all the [Configuration settings](https://minimo.netlify.com/docs/installation#configuration-for-minimo) of Minimo.

Also, old browsers that don't support [CSS var()](https://developer.mozilla.org/en-US/docs/Web/CSS/var#Browser_compatibility) won't show the custom color.

**Comment by jghauser** [comment]
@MunifTanjim sorry for the slow reply, I was waiting for the hugo package to be updated to 0.45 in the Arch repositories so I could generate the site with the newest theme. I'm happy to say it now works perfectly! I must have made some mistake when updating. Thanks!
