### ISSUE TITLE
Update config.toml

### ISSUE THREAD

**Issue by Fastidious** [MunifTanjim/minimo#108]
The repo and demo website are missing `recentPostsLength` configuration. Not sure if other option might be missing too. See [comment](https://github.com/MunifTanjim/minimo/commit/79f2e59f4a8badb064a5bf2cf3b2aae6e4b62058#commitcomment-28114341).

**Comment by MunifTanjim** [comment]
See [Widgets Configuration](https://minimo.netlify.com/docs/widgets/#widgets-configuration-file)
