### ISSUE TITLE
Add description to OpenGraph

### ISSUE THREAD

**Issue by Fastidious** [MunifTanjim/minimo#109]
Would it be nice to add a description to OpenGraph. Something like using a `description:` frontmatter, or using the "first X words" on an entry, or either! (configurable). That way Twitter cards would have a small verbose, and not just the title, and link.

**Comment by MunifTanjim** [comment]
Isn't description currently present in the OpenGraph template?

**Comment by Fastidious** [comment]
I am an idiot. The frontmatter `description` is indeed used (when it exists) on Twitter cards. I don't use Facebook, so I can't test, will it work similarly on that social network?

**Comment by MunifTanjim** [comment]
It should work. Let me know if it doesn't.

I'll close this issue now.
