### ISSUE TITLE
All entries, paginated

### ISSUE THREAD

**Issue by Fastidious** [MunifTanjim/minimo#110]
What would I have to do to get a paginated list of entries on the main page, instead of just the recent posts?

**Comment by MunifTanjim** [comment]
Override the `/layouts/index.html` and add these:

```html
<div class='container list-container'>
  <ul class='list'>
    {{ range .Paginator.Pages }}
      {{ .Render "li" }}
    {{ end }}
  </ul>

  {{ partial "nav/pagination" . }}
</div>
```

I hope that helps.

On a relevant note, this is not actually an issue. Actually, it's not even specific to Minimo. Any Hugo theme will need more-or-less the same template implementation for listing all entries on a paginated homepage. [Hugo Discussion Forum](http://discourse.gohugo.io/) is a great place for posting this type of questions.
