### ISSUE TITLE
Support staticman.net comments system

### ISSUE THREAD

**Issue by feng1st** [MunifTanjim/minimo#111]
Hi, @MunifTanjim, would you consider adding staticman.net comments system?

**Comment by MunifTanjim** [comment]
Can you show me an example theme so I can take a look at the implementation details?

Or, can you tell me what your expectation from this feature?

@feng1st

**Comment by feng1st** [comment]
I think <https://themes.gohugo.io/beautifulhugo/> has this feature.

**Comment by MunifTanjim** [comment]
Implemented in ffb8ecbbaf38dd8c72c9cf5006a269f7076a6b0e

**Minimo Documentation**:
- [Comments Support ](https://minimo.netlify.com/docs/comments-support/)

@feng1st
