### ISSUE TITLE
Multiple emojis next to each other bug

### ISSUE THREAD

**Issue by adamurban98** [MunifTanjim/minimo#114]
Placing **2 emojis next to each other** makes only the first to be rendered:
`:smiley: :smiley:` should render as ":smiley: :smiley:".
Instead it renders as  ":smiley: :<span></span>smiley:".

It seems that two emojis next to each other require some text in between them to be rendered correctly:
`:smiley: and :smiley:` renders to ":smiley: and :smiley:".

This fix seems to work, but spaces without \<span> are not enough:
`:smiley:<span></span> :smiley:` renders to ":smiley: :smiley:"

**Comment by MunifTanjim** [comment]
Which version of Hugo are you using? @adamurban98

**Comment by adamurban98** [comment]
Hugo Static Site Generator v0.36.

**Comment by MunifTanjim** [comment]
This bug is related to Minimo. It's a Hugo bug.

Try upgrading to Hugo v0.37.1.
