### ISSUE TITLE
Disqus not working 

### ISSUE THREAD

**Issue by eliocamp** [MunifTanjim/minimo#115]
Disqus comments were not working and I had to add a line to my config.toml 

```
[params.comments]
disqus = true
```

And change [this line](https://github.com/MunifTanjim/minimo/blob/ffb8ecbbaf38dd8c72c9cf5006a269f7076a6b0e/layouts/partials/entry/comments.html#L14) to

```
{{- $disqusEnabled := $config.disqus -}}
```

**Comment by MunifTanjim** [comment]
I've pushed a fix in c6caaefd1f37cca62a494200b01da3b71b65485b
