### ISSUE TITLE
Is there a setting to move the Main Menu to the sidebar?

### ISSUE THREAD

**Issue by TimothyBramlett** [MunifTanjim/minimo#119]
I would like to move the Main Menu to the sidebar.  Is there a setting to do this?

**Comment by MunifTanjim** [comment]
Well, not currently. But I'm gonna add it as soon as possible. :sweat_smile: 

Thanks for the suggestion.

**Comment by TimothyBramlett** [comment]
Awesome! :)

**Comment by MunifTanjim** [comment]
Take a look at the following documentation:

- [Menus](https://minimo.netlify.com/docs/menus/#sidebar-menu)
- [Widgets](https://minimo.netlify.com/docs/widgets/#widget-sidebar-menu)
