### ISSUE TITLE
Feature Request: Code syntax highlighting

### ISSUE THREAD

**Issue by shatgupt** [MunifTanjim/minimo#12]
Syntax highlighting using [prismjs](http://prismjs.com/) maybe?

EDIT: I can give it a shot it if you can guide me where to make changes 😄

**Comment by shatgupt** [comment]
Seems like we already have all the markup and just the prism css and js need to be included.
http://prismjs.com/#basic-usage

**Comment by MunifTanjim** [comment]
I've been thinking about adding an extensible solution for client-side syntax highlighting.

For now, as you want to use PrismJS, you can use the [customCSS & customJS](https://github.com/MunifTanjim/minimo/blob/2bc537fce37d45a3e9bfa06e01ea603284019e3e/exampleSite/config.toml#L20-L21) configuration options. Just add the css & js files' URL to the array. You can add multiple files.

**Comment by shatgupt** [comment]
It works with custom CSS and JS. Thank you.

**Comment by idevz** [comment]
what about highlighting nesting code surround with '``' ? I found that minimo can't parse this kind of markdown code.

**Comment by MunifTanjim** [comment]
@idevz Could you give me an example? I don't fully understand what you are trying to say.

But, markdown parsing is not something that the themes do. It's done by [blackfriday](https://github.com/russross/blackfriday) parser used by [Hugo](https://github.com/gohugoio/hugo).

**Comment by idevz** [comment]
@MunifTanjim  , Thanks a lot, One figure is worth thousand words :),

### my markdown code:

<img width="1035" alt="screen shot 2017-07-17 at 06 22 41" src="https://user-images.githubusercontent.com/2113827/28251834-71cec7dc-6ab8-11e7-8fb2-793b56a3438e.png">

### my minimo Blog:

<img width="887" alt="screen shot 2017-07-17 at 06 22 52" src="https://user-images.githubusercontent.com/2113827/28251833-71bf9afa-6ab8-11e7-9633-362e9a598d4f.png">

**Comment by MunifTanjim** [comment]
@idevz Oh, I see. That is by design, it just uses a slightly different font. But you can use custom CSS if you want to change that. You may want something like this:

```css
.entry-content {
  code {
    background: grey;
  }
}
```

If you need some help with using custom CSS - [see here](https://discourse.gohugo.io/t/minimo-css-customization/7173/4?u=muniftanjim).

**Comment by idevz** [comment]
@MunifTanjim Ok I know this, but a `monospace` font is not so obvious amount Chinese. 
And custom CSS is works to me, thank you

**Comment by siben168** [comment]
@MunifTanjim for code highlighting, how about use js libaray such as [highlightjs](https://highlightjs.org/)?  it requires much less work and i saw that is working on other themes.

**Comment by matrixik** [comment]
You always could use highlighter build into Hugo for off-line highlighting: https://gohugo.io/content-management/syntax-highlighting/

**Comment by MunifTanjim** [comment]
Solved by Hugo v0.28: [Syntax Highlighting](https://gohugo.io/content-management/syntax-highlighting/)
