### ISSUE TITLE
Make sidebar background and text color configurable 

### ISSUE THREAD

**Issue by wtip** [MunifTanjim/minimo#127]
It would be nice if the sidebar background color was configurable the same way `accentColor` is used. The text color should also be changeable.

**Comment by MunifTanjim** [comment]
I won't provide a way which can potentially result in a ugly looking theme.
If you need to change the sidebar background, use a custom css file.

Also, there's a shortcode [`text`](https://minimo.netlify.com/docs/shortcodes/#shortcode-text) for changing text color in your contents.

**Comment by wtip** [comment]
Is it possible to override a few CSS setting with the custom CSS or do I need to figure out how to build all the assets?

Could you possibly add a section to the readme on how to setup the build pipeline? I do not have experience with CSS minification. I guess I need to install node and install dependencies with yarn.

**Comment by wtip** [comment]
Nevermind. Looks like you answered this here 
https://discourse.gohugo.io/t/minimo-css-customization/7173/6

**Comment by MunifTanjim** [comment]
@wtip You can also use the `customCSS` option in your `config.toml` file to avoid building assets.

These links will give you the idea:
- https://github.com/MunifTanjim/minimo/issues/85#issuecomment-359287057
- https://github.com/MunifTanjim/minimo/issues/62#issuecomment-349193623
- https://github.com/MunifTanjim/minimo/tree/master/exampleSite
