### ISSUE TITLE
I18n for Dates

### ISSUE THREAD

**Issue by dalliard** [MunifTanjim/minimo#129]
First of all, thank you @MunifTanjim for the great theme.

I am from Switzerland and blog in German. It would be great to have the Dates also translated.

For example if I use the predefined Date Format it says "May" instead of "Mai" (German).

I will use a numbered Format like "02.01.06" for now. But would prefer to show the Month written.

**Comment by MunifTanjim** [comment]
`Go` (which is the language used to build `Hugo`) currently doesn't have internationalization support for DateTimes. So, there's no standard way of doing that.

But, if you need that, there's an example in Hugo docs about how to implement it: [Customize Dates](https://gohugo.io/content-management/multilingual/#customize-dates)

For Minimo, you'll need to override the following layout files:

- `/layouts/partials/entry/meta/posted-on.html`
- `/layouts/partials/list/date.html`
- `/layouts/partials/list/date.archive.html`

**Comment by dalliard** [comment]
Thank you so much! I will look into that. What files do I need to override to also change the Date in the Comment section?

**Comment by MunifTanjim** [comment]
https://github.com/MunifTanjim/minimo/blob/47418ca786eb5bfdf4c15904bf962c8985ae789b/layouts/partials/comments/staticman/comment.html#L24

Closing this issue now as i18n for datetime won't be implemented until `Go` & then `Hugo` supports it.

**Comment by VincentTam** [comment]
@ghost You may take a look at Beautiful Hugo's i18n if you like.
