### ISSUE TITLE
Addition of a dark theme (theme switcher button perhaps?)

### ISSUE THREAD

**Issue by xypnox** [MunifTanjim/minimo#131]
I would like to suggest the addition of a dark theme. It can be achieved using few simple css and js changes. I would link them here for reference. 

- [How to make changeable themes using CSS and JavaScript](https://stackoverflow.com/questions/8796107/how-to-make-changeable-themes-using-css-and-javascript) for theme switching
- [Window.localStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) for storing theme preferences throughout the site

I would love to implement this feature but I have limited knowledge about JS.

**Comment by MunifTanjim** [comment]
If you want to implement this, go ahead. Also make it completely optional, so that if somebody doesn't enable it, it won't affect them in any way.
And when you are done, you're welcomed to create a PR.

But, I don't have the time to work on this currently. Sorry.

Closing the issue now.
