### ISSUE TITLE
how can i put tags in menu?

### ISSUE THREAD

**Issue by hwdef** [MunifTanjim/minimo#132]
i want to put tags in menu like this picture , what shoud i do ?
![pic](http://ohwcthu7l.bkt.clouddn.com/1.png)

**Comment by MunifTanjim** [comment]
Reading documentations can get you a long way. Try this:

- https://gohugo.io/content-management/menus/

If you still can't figure it out after reading the documentation and trying it, let me know.

Closing the issue.

**Comment by hwdef** [comment]
do you offer this function in this theme？
i do not want to modify html file

**Comment by hwdef** [comment]
I know.
I'm sorry about that.
thank you very much.
