### ISSUE TITLE
taxonomyCloudShuffle = false not working

### ISSUE THREAD

**Issue by DevOpsEtc** [MunifTanjim/minimo#137]
I set the taxonomyCloudShuffle key value to false under param.settings in config.toml, but the tag cloud in the sidebar is still shuffling. I think I found the issue on line 7 in layouts/partials/widgets/taxonomy_cloud.html:
`{{- $shuffle := ( $config.shuffle | default true ) -}}`

My setting is respected if I change the line to:
`{{- $shuffle := ( .Site.Params.settings.taxonomyCloudShuffle | default true ) -}}`

Thanks for the great theme!

**Comment by MunifTanjim** [comment]
For `taxonomy_cloud` widget, change the configuration in your widget config file: `/data/config/widgets.toml`
ref: https://minimo.netlify.com/docs/widgets/#widgets-configuration-file

`.Site.Params.settings.taxonomyCloudShuffle` is used for the taxonomy list page (e.g.: https://minimo.netlify.com/tags/ )

Sorry for the confusion.

**Comment by DevOpsEtc** [comment]
Thanks, works great. Guess I'll read all of your documentation now!
