### ISSUE TITLE
How to center an image?  I'm used to Bootstrap :)

### ISSUE THREAD

**Issue by TimothyBramlett** [MunifTanjim/minimo#138]
Stupid question probably but What is the proper way to center an image?  Just use regular css?  I'm used to Bootstrap so I wanted to double check.

**Comment by dalliard** [comment]
Are you speaking about an image in your markdown file?

You could use a shortcode as described in the documentation [here](https://minimo.netlify.com/docs/shortcodes/). Like this:

````
{{% center %}}
![Your Image](/path/to/the/image.jpg)
{{% /center %}}
````

Let me know if that solves your problem. Happy to help!

**Comment by MunifTanjim** [comment]
- Use build-in `center` Shortcode (as @dalliard described)
- Create your own Hugo Shortcode
- Use custom CSS class

It's really up to you. Whatever you feel comfortable with. :slightly_smiling_face:
