### ISSUE TITLE
[feature request] search support

### ISSUE THREAD

**Issue by druxstr** [MunifTanjim/minimo#140]
Would be awesome if Minimo supported search, with a searchbox widget for instance. Very few Hugo theme provide a way to search within content :(

This would be really useful in Minimo, because if you don't use the taxonomy tag cloud, your old content quickly becomes hard to discover /or to find.

**Comment by dalliard** [comment]
I first implemented [this gist](https://gist.github.com/eddiewebb/735feb48f50f0ddd65ae5606a1cb41ae) from @eddiewebb. But found the solution, which is based on the linked gist, used in [after-dark](https://github.com/comfusion/after-dark#fuzzy-search) (fuzzy search) even better. The search itself isn't perfect, but it works. I wouldn't call the solutions minimalistic, cause both use some external JavaScript.

**Comment by MunifTanjim** [comment]
There are so many ways for adding search functionality in static sites. Any idea about which one to choose?

**Comment by lobopraveen** [comment]
For time being, I'm using a menu item that takes goes to https://www.google.com/search?q=site:praveenlobo.com.   See here : https://praveenlobo.com/

The easiest would be to expand on search link to show a text box to enter keyword and a button that takes you to Google search with `site` search type and keyword filled in. For e.g. if I entered "hugo" in the search box, it should take me to `https://www.google.com/search?q=site:praveenlobo.com+hugo` 

The search engine URL can be read from the config file so users can have an option to use search engine of their preference. This config item should be the URL to which the search text is appended and redirected. So, I would use `searchEngineURL = "https://www.google.com/search?q=site:praveenlobo.com+"`

**Comment by matrixik** [comment]
https://gohugo.io/documentation/ is using https://www.algolia.com/ref/docsearch
It have free tier.

**Comment by druxstr** [comment]
I'd say @dalliard 's solution looks fine. Any notable downside (beside external JS)?

With a searchbox widget that can be added to the sidebar / home, that would look great imo.

**Comment by MunifTanjim** [comment]
I'll implement it as soon as I get the time.

In fact, I'm thinking of implementing multiple options for it.
- Algolia
- Lunr.js
- Fuse.js (maybe)

**Comment by brianclemens** [comment]
+1 for Algolia support.  That thing is fast.  I've been trying to rip it out of the [bilberry theme](https://github.com/Lednerb/bilberry-hugo-theme)
