### ISSUE TITLE
main.css not correctly linked

### ISSUE THREAD

**Issue by Backtrennpapier** [MunifTanjim/minimo#141]
Hi,

I just upgraded to the latest hugo and minimo theme. The generation also with verbose output shows no errors.

But when looking at the style sheet and javascript reference in the index.html it generates an invalid link:
```
<link rel='stylesheet' href='/assets/css/%3cnil%3e'>
<script src='/assets/js/%3cnil%3e'>
```

The main css is correct placed in assets/css/main.cb99c271.css .

I assume this is a theme issue, but correct me if I'm wrong.

Thanks for you help!

**Comment by MunifTanjim** [comment]
Not a theme issue.

Can't say anything without knowing the Hugo version and taking a look at your site's repository.

**Comment by Backtrennpapier** [comment]
I updated to the latest go version and rebuild everything again from scratch and now it's working again. Sorry for troubling you, issue can be closed
