### ISSUE TITLE
issue with new authors social media links

### ISSUE THREAD

**Issue by snowyTheHamster** [MunifTanjim/minimo#144]
Hi, awesome theme!

I just tried a fresh install and followed your instructions on adding a new author.
I created a new author's toml file in the data folder and added the social information.

The link to the new author's page is created but
the social media icons links still points to what's in the config.toml [params.social]. 

Am I missing another step or can't the author's have their own links?

**Comment by MunifTanjim** [comment]
Social Menu will always take the values from `[params.social]` in `config.toml`.

The author's social information is used for [Opengraph Metadata](http://ogp.me/)

**Comment by snowyTheHamster** [comment]
Thanks for the quick reply!

Noted on the opengraph meta.
