### ISSUE TITLE
[Feature Request] Staticman German translation

### ISSUE THREAD

**Issue by tobiasmillauer** [MunifTanjim/minimo#146]
Please add support for Staticman with German translation strings or English as fallback. Thanks, Tobias 
 
<img width="732" alt="staticman-german" src="https://user-images.githubusercontent.com/30864119/41241137-86de8daa-6d9c-11e8-8c89-23090a19381f.png">

**Comment by MunifTanjim** [comment]
The support is already there. Hugo fallbacks to the language set by `defaultContentLanguage` in the `config.toml`.

But the German translation file is missing strings: [`/i18n/de.toml`](https://github.com/MunifTanjim/minimo/blob/85951fed1417f74e344d60111e320fa8579c37e2/i18n/de.toml) and I don't know the language.

So, nothing I can do about it. The language files are updated by the community. If you update it, consider creating a pull request after doing it. You can find the full list of strings in [`/i18n/en.toml`](https://github.com/MunifTanjim/minimo/blob/85951fed1417f74e344d60111e320fa8579c37e2/i18n/en.toml) file.

**Comment by tobiasmillauer** [comment]
Thanks, I've translated the strings and created a pull request https://github.com/MunifTanjim/minimo/pull/147 ;)

**Comment by tobiasmillauer** [comment]
Thanks for the hint, I've added them in https://github.com/MunifTanjim/minimo/pull/148.
