### ISSUE TITLE
Error failed to read social.base* Expected value but '\' found instead

### ISSUE THREAD

**Issue by jlosito** [MunifTanjim/minimo#150]
When using the minimo theme and building my Hugo project, I am receiving the following error.
```
Building sites … ERROR 2018/06/19 10:34:05 Failed to read data from theme.toml/theme.toml: Near line 2, key 'social.base.codepen': Near line 2: Expected value but found '\'' instead.
```
Even though this is listed as an error, this does not cause my build to fail as shown in the output below.

```
                   | EN  
+------------------+----+
  Pages            | 26  
  Paginator pages  |  1  
  Non-page files   |  0  
  Static files     | 19  
  Processed images |  0  
  Aliases          |  2  
  Sitemaps         |  1  
  Cleaned          |  0  

Total in 97 ms

```

Below is the the structure of my .gitmodules
```
[submodule "themes/minimo"]
         path = themes/minimo
         url = https://github.com/MunifTanjim/minimo
```

Below is the structure of my config.toml less some information.
```
# https://gohugo.io/getting-started/configuration/
# https://github.com/MunifTanjim/minimo/blob/master/exampleSite/config.toml

languageCode = "en-us"
title = "Open Practice Library"
theme = "minimo"
# Why "docs" and not "public"? https://git.io/vXzj6
publishDir = "docs"
canonifyURLs = true

[params.assets]
customCSS = ["css/custom.css"]

[permalinks]
page = "/:slug/"                    
```

**Comment by MunifTanjim** [comment]
That still doesn't explain why the error occurred. Can you provide some more information?

Operating system:
Hugo version:

**Comment by jlosito** [comment]
I'm currently running Fedora 28 with v0.37.1 of Hugo. 

I just made a new project using the exampleSite and was able to reproduce the error. It happens when one does not set the params.social in the config.toml file of the parent project using the theme. I'm guessing the error in the original post I am referring to the handles not being set as well as social_menu.html not checking if the key is set before creating the hyper-link.

**Comment by MunifTanjim** [comment]
Can't reproduce the issue with Hugo v0.42.1

But merging the related PR anyway.

Thanks :slightly_smiling_face:
