### ISSUE TITLE
Bigger fonts of source blocks on high sierra

### ISSUE THREAD

**Issue by measpear** [MunifTanjim/minimo#152]
Hi,
Compared to other os (ubuntu and windows), fonts of the source blocks and emphasized text (ex config.toml in the sccreenshot below) on macos high sierrra are more larger. Is it possible to make these larger fonts smaller when the system is macos?
<img width="1280" alt="mac_view" src="https://user-images.githubusercontent.com/2395948/41639492-a465ce30-7466-11e8-8191-b9c3d2a4642f.png">

**Comment by MunifTanjim** [comment]
I don't think that's possible. But I can be wrong. :slightly_smiling_face:
