### ISSUE TITLE
Add customizable "extra" in header and footer

### ISSUE THREAD

**Issue by Schnouki** [MunifTanjim/minimo#156]
Hi,

I need to add an external JavaScript to my page header (basically `<script async src="//cdn.<somesite>/embed.js"></script>`). At the moment, to do this, I have to copy/paste `layout/partials/head/includes.html` in my blog and edit it to add my stuff. This makes it harder to upgrade to a newer version of Minimo since I'll need to update the content of `includes.html` if it is updated...

A better (IMHO) solution would be to add an *empty* `layout/partials/head/extra.html`, included at the end of `includes.html`, that is designed to be overridden (it could even be specified in a comment). And possibly the same thing in the footer in case people need that too.

Does that make sense to you? Would you be willing to do it or to merge a PR implementing this?

**Comment by MunifTanjim** [comment]
> add an empty `layout/partials/head/extra.html`, included at the end of `includes.html`

Add that in the `head.html` before the closing head tag.

And for the footer, include `layout/partials/footer/extra.html` at the end of `scripts.html`

You can go ahead and create a PR.

**Comment by Schnouki** [comment]
At the end of `scripts.html` or in `footer.html` after the inclusion of `scripts.html`?

**Comment by MunifTanjim** [comment]
I think at the end of `scripts.html` should do fine. Because, there shouldn't be any structural html elements in that partial as that would break the theme's style. What do you think?

**Comment by Schnouki** [comment]
Well, there *could* be HTML elements with the appropriate style (for instance the infamous EU cookie banner with a `position: fixed`)... but that could be done in a widget anyway. So `scripts.html` it is!

**Comment by MunifTanjim** [comment]
Well, if you think `footer.html` is more appropriate, go for it. I don't have any problem with that. :slightly_smiling_face:
