### ISSUE TITLE
Translation of taxonomy terms

### ISSUE THREAD

**Issue by Guilz** [MunifTanjim/minimo#160]
Hello there,

I am trying to do exactly what is described [here](https://discourse.gohugo.io/t/translate-tags-taxonomies/9722): translating taxonomy terms (in my case, categories and tags, but that could be anything else). And I have the same problem: taxonomy terms won't translate, no matter what I write in `i18n/my-language.toml`.

I understand the principle of the [suggested solution](https://discourse.gohugo.io/t/translate-tags-taxonomies/9722/3), and I know it should be possible to write my own templates and make them take precedence over the ones in Minimo (that's the way Hugo works), but I have near-zero experience with web design (which is why I am using an already made theme and not designing my own) and I am unable to figure out which template files I need to customize.

Would it be possible to add the capability to translate taxonomy terms to Minimo?
Thank you so much in advance.

**Comment by MunifTanjim** [comment]
> taxonomy terms won't translate, no matter what I write in i18n/my-language.toml.

`i18n` directory is not generally for translating contents.

> I have near-zero experience with web design (which is why I am using an already made theme and not designing my own) and I am unable to figure out which template files I need to customize.

You don't need to touch any template files for doing what you want.

Let's see an example:

Suppose, you want to translate a **category** named `movie`. Just create a file (for English): `/content/categories/movie/_index.en.md` with the following frontmatter:

```yaml
title: Movie (in english)
```

And for French, create a file: `/content/categories/movie/_index.fr.md` with the following frontmatter:

```yaml
title: Movie (in french)
```

You can do this for any Language and any taxonomy terms.

Let me know if you had any problem.

**Comment by Guilz** [comment]
Ah, this point was completely unclear to me from Hugo's documentation. Thank you, that's very helpful and it indeed works fine this way.

**Comment by Guilz** [comment]
Reopening this, because I noticed something doesn't work with multilingual taxonomies. Here is an example.

I have a tag `hiking` and its `fr` translation `randonnees`, set up this way: default language is `en`, and I have `content/tags/hiking/_index.fr.md`. This file contains:

```
---
title: Randonnées
slug: randonnees
---
```

I also have this in my `config.toml`:

```
[permalinks]
tags = "/tags/:slug/"
```

And in my posts, I have `hiking` listed in `tags` in the front matter.

**What should happen:** in the `fr` version of the site, the page `example.com/fr/tags` should have tags listed in French, and clicking such tags should direct to their `fr` `slug`.

**What happens instead:** on the page `example.com/fr/tags`, tags are displayed correctly (i.e. they are translated OK), but clicking on them directs to their `slug` in the default language (which I also set explicitly in `content/tags/hiking/_index.md`), and because this path is not built under `fr` this leads to a page not found. If I edit the URL to replace the default language `slug` by the translated `slug`, I can get the term page to display fine (so it is built correctly, simply not linked to correctly).

This time it seems it's because of a template not following the permalink settings.

I hope you can help with that.

**Comment by MunifTanjim** [comment]
@Guilz this should solve the issue.

**Comment by Guilz** [comment]
It solved it, thank you. 👍
