### ISSUE TITLE
.Site.GetPage with more than 2 arguments will not work on v0.45 or later

### ISSUE THREAD

**Issue by j1mc** [MunifTanjim/minimo#162]
There appear to be at least two files that use this feature to populate the taxonomy cloud:

`layouts/partials/entry/taxonomy-list.html`
and
`layouts/partials/extras/taxonomy_cloud.html`

These two templates will need to be adjusted to accommodate the changes with 0.45. See the `notes` section of the 0.45 [release announcement](https://github.com/gohugoio/hugo/releases/tag/v0.45) for further information.

Thanks for all of your work on this project!!

**Comment by MunifTanjim** [comment]
Thanks @j1mc

The latest release should fix that.
