### ISSUE TITLE
Possible support of KaTeX?

### ISSUE THREAD

**Issue by Guilz** [MunifTanjim/minimo#163]
Hello there,

It's great that we have different options for the search module. Thinking along the same lines, what about adding support for [KaTeX](https://khan.github.io/KaTeX/)?
This is a math rendering library that sells itself as much faster than MathJax (although not supporting as much of LaTeX, if I understood correctly what I read about it).

Just an idea. 😃

**Comment by MunifTanjim** [comment]
@Guilz It actually is much faster! Thanks for the suggestion :smiley:
