### ISSUE TITLE
Security vulnerability with package-lock.json

### ISSUE THREAD

**Issue by raheems** [MunifTanjim/minimo#164]
I get this message in my github repository. I am not sure how to update that. Any thoughts? Thank you.

We found a potential security vulnerability in one of your dependencies.
A dependency defined in …/minimo/package-lock.json has known security vulnerabilities and should be updated.

Only the owner of this repository can see this message.
Learn more about vulnerability alerts

**Comment by MunifTanjim** [comment]
I'm well aware of that. There's vulnerability in some dependencies of `node-sass` package.

And it's not a concern. But I'll try to update the packages. Thanks.
