### ISSUE TITLE
Google adsense support

### ISSUE THREAD

**Issue by raheems** [MunifTanjim/minimo#165]
I was wondering if google adsense support is available in the theme. Could you give me some clues? Thank you.

**Comment by MunifTanjim** [comment]
I'm not super familiar with Google Adsense. And I won't be implementing it in this theme.

If you need that, I'll suggest to:

- Use the [`extra` partial](https://github.com/MunifTanjim/minimo/pull/158) in footer for adding scripts.

- Use a custom [widget](https://github.com/MunifTanjim/minimo/tree/master/layouts/partials/widgets) (for placing ads in sidebar or footer) or a [shortcode](https://gohugo.io/content-management/shortcodes/) (for placing ads in contents). You can also override other [templates](https://gohugo.io/templates/) if you want to place the ads elsewhere.
