### ISSUE TITLE
Support of custom GitLab instance in social menu

### ISSUE THREAD

**Issue by Guilz** [MunifTanjim/minimo#166]
Hello,

Right now, the gitlab.com instance is hardcoded for the social menu, i.e. when you specify your gitlab username in `config.toml` the link in the social menu becomes https://gitlab.com/your-username.

But GitLab can be installed by anyone, and the GitLab account one wants to list in their social menu might not be on the gitlab.com instance but on a different instance.

I propose to make it possible to specify an instance in `config.toml`, by filling this field of the config file as follows and have the link set appropriately in the social menu:

```
[params.social]
gitlab = "other-instance.com/username"
```

A reasonable default in case no instance is specified (easy to detect: this field would not contain a slash in that case) would be to assume the instance is gitlab.com. For users already having their gitlab.com account listed in their social menu, this would allow updating minimo without having to update their config.

Thank you in advance.

**Comment by MunifTanjim** [comment]
I don't want to introduce unnecessary complexity to the templates. For your use case, just do the following:

- Copy the **`/themes/minimo/data/theme.toml`** file to **`/data/theme.toml`**
- Change the value for `social.base.gitlab`

I hope that helps.

**Comment by Guilz** [comment]
That helps, thank you. 😃
