### ISSUE TITLE
How to compile/build?

### ISSUE THREAD

**Issue by stevenringo** [MunifTanjim/minimo#168]
Hi,

This an awesome theme. Looks great and has fantastic features. Well done.

I would like to propose some enhacements, however I am unfamiliar with how you compile/build your asset pipeline. Would you have some instructions on how to build/preview the theme itself?

For example I would like to experiment with a no-sidebar layout that keeps the search box in the right-hand corner of the top menu.

I would also like to change the fonts and colours for syntax highlighting. I realise in some instances it's possible to override the CSS but I would like to have it that one could, for example, set config options  for different Chroma styles, or specify a font stack directly in `config.toml`.

If there is a way I can make these changes using your build system that would be awesome. I notice there is a `webpack.config` file, but unsure what your workflow for compiling, previewing etc looks like.

Any help will be much appreciated. Thanks so much.

Steve

**Comment by MunifTanjim** [comment]
The build steps are basically just:

```
# install the dependencies
npm install

# build the assets for production
npm run build

# watch and build the assets for development
npm run watch
```

---

About syntax highlighting, Hugo already offers various customization options (ref: [Syntax Highlighting](https://gohugo.io/content-management/syntax-highlighting) ). You can use the custom syntax styles with `customCSS` option in `config.toml` file.

And for other things you mentioned, I think it's better to discuss them in separate issues.
