### ISSUE TITLE
Bug: Footnote link is not right

### ISSUE THREAD

**Issue by jostyee** [MunifTanjim/minimo#17]
Hugo has built-in Footnote support, 
![image](https://user-images.githubusercontent.com/88564/28974428-0033c4fe-78fc-11e7-9951-ff70c9bd59b8.png)

`minimo` can generate footnote, too. But its link is broken. For example, add one to post `post/test_footnote/` :
```
test[^cfg]
```

`hugo server -w` would generate a footnote link as `localhost:1313/#fn:cfg` instead of the correct one `localhost:1313/post/test_footnote/#fn:cfg`

**Comment by MunifTanjim** [comment]
Hugo themes never generate any built-in markdown features. This is probably an issue with the version of Hugo you are using.

Anyway, have you tried any other themes? If you have, do they generate footnote from your contents alright?

**Comment by jostyee** [comment]
That's the weird part, I tried https://github.com/zhe/hugo-theme-slim and same version Hugo generates the right codes.

**Comment by MunifTanjim** [comment]
Can you share your site's repository?

**Comment by jostyee** [comment]
https://github.com/jostyee/hugo_test

can be reproduced at my env: `Hugo Static Site Generator v0.26-DEV darwin/amd64 BuildDate: 2017-08-02T18:02:22+08:00`

**Comment by MunifTanjim** [comment]
```html
<base href='{{ .Site.BaseURL }}'>
```
This line in **`/layouts/partials/head/head.html`** is causing the problem. For now, remove this line and you are good to go.

Before I can update the theme's repository, I'll need to check the whole theme to make sure removal of this line doesn't cause any other problems.
