### ISSUE TITLE
Sitewide opengraph image

### ISSUE THREAD

**Issue by raheems** [MunifTanjim/minimo#171]
Is it possible to add a sitewide opengraph image? 
Currently, the opengraph image can be added to contents but wondering how to enable it for the site itself.

**Comment by MunifTanjim** [comment]
Right now, opengraph images are pulled from:

- `.Params.cover` (content frontmatter)
- `.Params.images` (content frontmatter)
- Gravatar for author's email address stored in `/data/authors/<id>.toml` (if the previous two options are missing)

If you want to add a always present opengraph image, you can use the **[`extra` partial for head](https://github.com/MunifTanjim/minimo/blob/d4799c3fb33f0f675efd68146fc6015ff87ed562/layouts/partials/head/extra.html)** to add something like:

```html
<meta property='og:image' content='{{ "path/to/image.png" | absURL }}'>
```

**Comment by raheems** [comment]
This works. Thank you!
