### ISSUE TITLE
Right to left languages support

### ISSUE THREAD

**Issue by akb1697** [MunifTanjim/minimo#177]
Thanks to all contributors who have and still working on this theme!
I just want to request a new feature, Is it possible the theme supports right to left languages (e.g Arabic, Hebrew).

**Comment by MunifTanjim** [comment]
@akb1697 can you check the PR?

**Comment by akb1697** [comment]
@MunifTanjim I have checked the PR. I will tested it out with Arabic language, and edit what I can (a newbie in Hugo unfortunately) 😀
