### ISSUE TITLE
Changing taxonomy URLs

### ISSUE THREAD

**Issue by Guilz** [MunifTanjim/minimo#178]
Certain URLs can be set arbitrarily with a `slug`, for example those of any page under `content/page` or `content/blog`, while some other cannot. I tried to specify a `slug` for the following pages, but none of them was taken into account, the pages are built with the default URL, ignoring my customization:

- `content/tags/_index.md`
- `content/categories/_index.md`
- `content/authors/_index.md`

Would it be possible to build the URLs of these pages based on the value of their `slug`?

**Comment by MunifTanjim** [comment]
Try these options in `config.toml`:

```toml
[permalinks]
authors = "..."
categories = "..."
tags = "..."
```

Other than that, I can't help you. Maybe other people can.

_It's not a theme specific issue, it's common for any Hugo sites_. So, try asking/searching in [Hugo Forum](http://discuss.gohugo.io) about "**how to change taxonomy urls?**"
