### ISSUE TITLE
Add support for Micro.blog web site verification

### ISSUE THREAD

**Issue by kaiwei** [MunifTanjim/minimo#180]
https://github.com/frjo/hugo-theme-zen seems to be the only Hugo theme with builtin support for Micro.blog so far. It will be great if Minimo can do the same!

http://help.micro.blog/2017/web-site-verification/

**Comment by MunifTanjim** [comment]
Nope. I don't think this is something that a theme should include. Not gonna do that, sorry.

But the **[`extra` partial for head](https://github.com/MunifTanjim/minimo/blob/d4799c3fb33f0f675efd68146fc6015ff87ed562/layouts/partials/head/extra.html)** was included in Minimo for these kind of things. Feel free to use that.
