### ISSUE TITLE
Sticky Navbar

### ISSUE THREAD

**Issue by Pankratius** [MunifTanjim/minimo#182]
Hi, 
thank you so much for this beautiful theme!
Is it possible to modify the navigation bar, so that it sticks to the top of the page while scrolling down?

**Comment by danielkdewar** [comment]
@Pankratius you need to change the sidebar position from `absolute` to `fixed` in the main.css file.

**Comment by MunifTanjim** [comment]
@Pankratius Use `customCSS` for adding CSS for sticky sidebar. It isn't something that's going to be available out-of-the-box for Minimo anytime soon.
