### ISSUE TITLE
Support for .Rmd files

### ISSUE THREAD

**Issue by raheems** [MunifTanjim/minimo#183]
I would like to request for support for .Rmd files with this theme. 

For now, the `toc: true`

does not work for .Rmd files

I am using Rmarkdown and processing the files with blogdown R-package within Rstudio.

**Comment by MunifTanjim** [comment]
Not an issue for a Hugo theme to handle.

**Comment by raheems** [comment]
I get that but many would use these theme with Rmd files. Hugo academic theme has this functionality.

**Comment by MunifTanjim** [comment]
I don't see how that's possible. Minimo is just a theme. It doesn't render the content.
