### ISSUE TITLE
KaTeX-Environments don't work

### ISSUE THREAD

**Issue by Pankratius** [MunifTanjim/minimo#187]
According to the [KaTeX-Documentation](https://katex.org/docs/supported.html#environments) it is possible to have environments like `bmatrix` or `aligned` in KaTeX. 
I tried this in the example site document, but it did not render, and just showed the plain KaTeX-code.
Is there a way to fix this?

**Comment by MunifTanjim** [comment]
- Update the theme to latest commit: d2587aafcbe24f66a3bfdba225da0c83334e2515
- Follow the latest documentation for using KaTeX with Minimo: https://minimo.netlify.com/docs/katex-support.

**Note**: You don't need to change the all your previous markdown contents to use the new `katex` shortcode. Previous syntax will continue to work.
