### ISSUE TITLE
Authors: error calling index: value has type uint8; should be string

### ISSUE THREAD

**Issue by pat-s** [MunifTanjim/minimo#188]
When rendering an .Rmd` file I get the following:

```sh
ERROR 2018/10/14 01:10:26 Error while rendering "page" in "docs/": template: 
_default/single.html:1:3: executing "_default/single.html" at <partial "header" .>:
 error calling partial: template: partials/header.html:4:3: executing 
"partials/header.html" at <partial "head/head" ...>: error calling partial: 
template: partials/head/head.html:2:5: executing "partials/head/head.html" at 
<partial "head/meta" ...>: error calling partial: template: 
partials/head/meta.html:6:3: executing "partials/head/meta.html" at <partial 
"head/opengr...>: error calling partial: template: 
partials/head/opengraph.html:1:38: executing "partials/head/opengraph.html" at 
<partial "data/title"...>: error calling partial: template: 
partials/data/title:23:31: executing "partials/data/title" at <partial 
"data/author...>: error calling partial: template: 
partials/data/author/displayName:13:21: executing 
"partials/data/author/displayName" at <index $author $lang>: error calling index: 
index of untyped nil
```

Header of .Rmd post:

```yml
authors: ["patrick"]
date: 2018-07-25
```

`data/authors/patrick.toml`:

```toml
id = "patrick"

[name]
display = "Patrick"
```

No custom `partials/data/author/displayName`.

Looks similar to #185

**Comment by MunifTanjim** [comment]
@pat-s

- Which version of Hugo are you using?
- Can you show me an example repo with the bug?

**Comment by pat-s** [comment]
Hugo 49.2

I just pushed to branch, sorry for not including it directly: https://github.com/mlr-org/mlr-web/tree/minimo

In theory there is also a netlify preview but it currently renders a broken site even though its working locally: https://5bc302824ed62f5ff8f0811f--mlr-web.netlify.com/

**Comment by pat-s** [comment]
Ok I got the error: The `data/authors/<id>` has to be the same as `authors: [<id>]`. 

For some reason I still had different values there. Sorry for the trouble. 
Thanks for the great theme!
