### ISSUE TITLE
baseURL causes troubles with css and js files

### ISSUE THREAD

**Issue by pat-s** [MunifTanjim/minimo#189]
related to https://github.com/budparr/gohugo-theme-ananke/issues/97

I was struggling for hours realizing that specifying a baseURL causes localization problems when running `hugo`.

Everything works fine without a baseURL set. 
Working commit: https://github.com/mlr-org/mlr-web/tree/d7b6e2db7648822103d7a6ef993ed147b3179340
commit with CSS issues: https://github.com/mlr-org/mlr-web/tree/3d3601c043b153f133f7bff63fe2e785f513fddb

Problematic build preview: https://5bc34fcfb13fb16d58c05a72--mlr-web.netlify.com/

**Comment by MunifTanjim** [comment]
@pat-s maybe because your `baseURL` is not correct? 

https://github.com/mlr-org/mlr-web/blob/3d3601c043b153f133f7bff63fe2e785f513fddb/config.toml#L1

It's missing a slash (`/`)

**Comment by pat-s** [comment]
Oh no.... :man_facepalming:

hours... :laughing:
