### ISSUE TITLE
Feature Request: LinkedIn

### ISSUE THREAD

**Issue by tobiasmillauer** [MunifTanjim/minimo#19]
Would you be so kind to integrate LinkedIn? :)

**Comment by MunifTanjim** [comment]
The icon-font used in Minimo is [Feather](https://github.com/colebemis/feather). Sadly, Feather still don't have [LinkedIn](https://github.com/colebemis/feather/issues/77) icon. So, if you want to add LinkedIn icon, you will have to manually add it to this file: [svg/icons.html partial](https://github.com/MunifTanjim/minimo/blob/3a26325f55f460b34708e1259df21293eb468151/layouts/partials/svg/icons.html).

**Comment by tobiasmillauer** [comment]
Thanks, I've the found the corresponding issue: https://github.com/colebemis/feather/issues/77

**Comment by alexkokkinos** [comment]
#25
