### ISSUE TITLE
Vulnerable dependencies

### ISSUE THREAD

**Issue by pat-s** [MunifTanjim/minimo#190]
I got this alert today in my repo:

![selection_021](https://user-images.githubusercontent.com/8430564/47033323-c701de00-d174-11e8-8359-b797e5a55f2f.png)

Is is possible to update those?

![selection_022](https://user-images.githubusercontent.com/8430564/47033376-e7319d00-d174-11e8-869a-a16de9b922ae.png)

cryptiles -> 4.1.2
hoek -> 4.2.1

**Comment by MunifTanjim** [comment]
Duplicate of #164 

Those are just couple of dependencies of `node-sass` package, which itself is a development time dependency. 

Don't worry about it, none of that is going to end up in the final product.

If the fix is available for those dependencies, I'll update them.
