### ISSUE TITLE
how to show tags and categories together in sidebar

### ISSUE THREAD

**Issue by mibesr** [MunifTanjim/minimo#192]
how to do it? thanks.

**Comment by MunifTanjim** [comment]
The [widget areas](https://minimo.netlify.com/docs/widgets/#available-widget-areas) in Minimo are pluggable. That means you can easily create new widgets and add them in the widget areas.

You can take inspiration from the [available widgets](https://minimo.netlify.com/docs/widgets/#available-widgets). The codes for them are stored in [`layouts/partials/widgets`](https://github.com/MunifTanjim/minimo/tree/master/layouts/partials/widgets) directory.

For you issue, here are the steps:

- Copy the `/themes/minimo/layouts/partials/widgets/taxonomy_cloud.html` file and paste it as `/layouts/partials/widgets/cat_cloud.html`.
- Find and replace all the `.widgets.taxonomy_cloud` occurrence to `.widgets.cat_cloud` inside the `cat_cloud.html` file.
- Add a config section `[cat_cloud]` for the new widget at the end of `/data/config/widgets.toml` file (it'll be similar to `[taxonomy_cloud]` section).
- Now you have a new widget called `cat_cloud`!
- Add the `cat_cloud` widget to the `sidebar` in `config.toml` file.
