### ISSUE TITLE
[Question] Support for Staticman nested comments

### ISSUE THREAD

**Issue by VincentTam** [MunifTanjim/minimo#197]
Hi, this is the author of halogenica/beautifulhugo#222.

Anyone using this theme would like to have support for nested comments?

![Staticman nested reply demo](https://user-images.githubusercontent.com/5748535/48619278-4533e900-e99c-11e8-9b43-c25f5939401b.png)
My Staticman demo site on Git*Lab*: https://vincenttam.gitlab.io/bhdemo served by @staticmanlab.

# Background [TL;DR]

Observing that the nested comments implemented on Network Hobo (Staticman's README "Useful links") contains a logic error, I've published the linked PR.

![staticman nested comments logic error](https://vincenttam.gitlab.io/post/2018-11-17-nested-comments-in-beautiful-hugo/networkhobo.png)
Everyone replies to the same person? (Dan replies to Dan?)

**Comment by MunifTanjim** [comment]
What's this about? :confused:

**Comment by VincentTam** [comment]
Comment with reply support.

**Comment by MunifTanjim** [comment]
For what? This theme already has nested Staticman comment support.

And this is not a place polls.

**Comment by VincentTam** [comment]
I didn't see that from this theme's README and demo.  Sorry about that.

I suppose GitHub issues is a place for discussion about a project, such as eduardoboucas/staticman#22.

**Comment by MunifTanjim** [comment]
It's okay. I appreciate your interest. Don't be sorry. :slightly_smiling_face: 

Well, it really depends on the maintainers of specific projects, how they utilize the issues section on Github.
