### ISSUE TITLE
Bug: minimo doesn't support code syntax

### ISSUE THREAD

**Issue by jostyee** [MunifTanjim/minimo#20]
https://daringfireball.net/projects/markdown/syntax#code
> To indicate a span of code, wrap it with backtick quotes (`).

But w/ minimo theme \`code\` will be rendered as plain text.

**Comment by MunifTanjim** [comment]
That is not correct. And also, Hugo Themes have nothing to do with rendering markdown.

Minimo styles the `code` tag with only `monospace` font-family. If you need something more (like: different background color), you can use customCSS with Minimo.
