### ISSUE TITLE
Error: Cannot find module 'glob' (lunr.js)

### ISSUE THREAD

**Issue by gour** [MunifTanjim/minimo#200]
Hello,

I'm trying to use Lunr.js to provide search on my site, but have the following problem:
```
$ node themes/minimo/scripts/generate-search-index-lunr.js 
internal/modules/cjs/loader.js:605
    throw err;
    ^
Error: Cannot find module 'glob'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/gour/prj/hugo/net/themes/minimo/scripts/generate-search-index-lunr.js:4:14)
    at Module._compile (internal/modules/cjs/loader.js:722:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
```

I'm using latest version of the theme along with: 

```
$  hugo version
Hugo Static Site Generator v0.52/extended linux/amd64 BuildDate: unknown
```
Not overly familiar with node packages, but here is the output:

```
$ npm list -g glob
/usr/lib
├─┬ asar@0.14.5
│ ├── glob@6.0.4 
│ └─┬ mksnapshot@0.3.1
│   └─┬ fs-extra@0.26.7
│     └─┬ rimraf@2.6.2
│       └── glob@7.1.3 
├── glob@7.1.3 
└─┬ npm@6.4.1
  ├─┬ cacache@11.2.0
  │ └── glob@7.1.2  deduped
  ├── glob@7.1.2 
  ├─┬ init-package-json@1.10.3
  │ └── glob@7.1.2  deduped
  ├─┬ node-gyp@3.8.0
  │ ├── glob@7.1.2 
  │ └─┬ rimraf@2.6.2
  │   └── glob@7.1.2  deduped
  ├─┬ npm-registry-fetch@1.1.0
  │ └─┬ make-fetch-happen@3.0.0
  │   └─┬ cacache@10.0.4
  │     └── glob@7.1.2  deduped
  ├─┬ pacote@8.1.6
  │ └── glob@7.1.2  deduped
  ├─┬ read-package-json@2.0.13
  │ └── glob@7.1.2  deduped
  └─┬ rimraf@2.6.2
    └── glob@7.1.2  deduped
```

Any hint what might be wrong?

**Comment by MunifTanjim** [comment]
Can you give me a link to your repository?

**Comment by MunifTanjim** [comment]
@gour The most probable cause is, Node.js can't find the global installation folder. In that case, set the Environment Variable `NODE_PATH` to `/usr/lib/node_modules` as your global packages are in that directory.

So, `NODE_PATH=/usr/lib/node_modules node themes/minimo/scripts/generate-search-index-lunr.js`

**Comment by gour** [comment]
> So, NODE_PATH=/usr/lib/node_modules node themes/minimo/scripts/generate-search-index-lunr.js

That helps in a sense there is no more exception thrown, but no `Lunr.js Index Generated for: /search/index.json` is shown.

I see that `index.json` is generated, but the search does not yield any result...in any case I'll investigate further what is the problem...

**Comment by MunifTanjim** [comment]
If you can share your repository, I could help you resolve the problem.

**Comment by gour** [comment]
> If you can share your repository, I could help you resolve the problem.

Well, I'm testing with your example site on my desktop machine and will include tarball of the site.
[test.zip](https://github.com/MunifTanjim/minimo/files/2689646/test.zip)

**Comment by MunifTanjim** [comment]
@gour Sorry about that. Turns out there was a bug in the scripts. I've pushed the fix. Can you try now, with the latest commit?

**Comment by gour** [comment]
> Can you try now, with the latest commit?

Now the script generates 

```
Lunr.js Index Generated for: /search/index.json
```

output, but the script still requires `NODE_PATH=/usr/lib/node_modules` and no pages are required when searching?

**Comment by MunifTanjim** [comment]
> the script still requires NODE_PATH=/usr/lib/node_modules

That's a Node.js thing. Either you install the packages locally (without the `-g` flag) or install them globally (with the `-g` flag) and set `NODE_PATH` environment variable accordingly.

> no pages are required when searching?

What do you mean by no pages are required?

**Comment by MunifTanjim** [comment]
I tested with the latest commit and it actually is working.
You're seeing "no pages are found" because Lunr.js result is saying so. Try to search words that are in the posts' titles, they should appear in the result.

The script included with Minimo for Lunr.js index generation is just a basic implementation, you can tweak it according to your own need. You'll have to read through these docs: https://lunrjs.com/guides/getting_started.html

With a bit of fine-tuning the results should be better. But I'm don't have much experience to help you any further with that :sweat_smile: 

Good luck.

If the issue is solved, I'd like to close it.

**Comment by gour** [comment]
> You're seeing "no pages are found" because Lunr.js result is saying so. Try to search words that are in the posts' titles, they should appear in the result.

I simply do not get any hit when using exact words from your blog posts...

> If the issue is solved, I'd like to close it.

Yes, you can close it since 'no hits' is not a part of this issue. ;)
