### ISSUE TITLE
How to change breadcrumbs Home title?

### ISSUE THREAD

**Issue by pontakornth** [MunifTanjim/minimo#201]
I don't really know if this related to theme or Hugo. About the site hierachy in your web is like this

Home > Docs

but my one is like this

MMK(site title) > whatever

and I have no idea how to change it.

**Comment by MunifTanjim** [comment]
I don't know what you mean by **site hierarchy** :thinking:

**Comment by pontakornth** [comment]
I mean the breadcrumb.

**Comment by MunifTanjim** [comment]
Set `title` or `linkTitle` in the markdown file's frontmatter. If both `title` & `linkTitle` is set, `linkTitle` is gets priority.

```md
---
title: Home
linkTitle: Home
---
```

In most cases, you site's homepage's markdown file will be `/content/_index.md`
