### ISSUE TITLE
Support for Valine

### ISSUE THREAD

**Issue by VincentTam** [MunifTanjim/minimo#203]
[Valine](https://valine.js.org/) is a JS commenting system _without_ backend licensed under GPLv2.  It's quite simple to implement.  As a result, it has attracted many netizens.

As can be seen in [Jekyll TeXt Theme](https://github.com/kitian616/jekyll-TeXt-theme), it's not so difficult to implement.

**Comment by MunifTanjim** [comment]
@VincentTam, would you like to create a PR for this?

**Comment by VincentTam** [comment]
Sorry, I'll leave this for other interested Valine users since I use this theme with Staticman on https://staticman-gitlab-pages.frama.io/minimo/
