### ISSUE TITLE
A question on search

### ISSUE THREAD

**Issue by Fastidious** [MunifTanjim/minimo#204]
This is a question on #155; is search working? I can't get results on any query on the [demo website](https://minimo.netlify.com).

**Comment by jhabdas** [comment]
Ditto. Searched for "katex" from sidebar widget. Landed on search page. Number of results not indicated.

**Comment by jhabdas** [comment]
Ditto. Searched for "katex" from sidebar widget. Landed on search page. Number of results not indicated. No results shown.

**Comment by jhabdas** [comment]
Ditto. Searched for "katex" from sidebar widget. Landed on search page. Number of results not indicated. No results shown.

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 YaBrowser/18.11.1.716 Yowser/2.5 Safari/537.36

**Comment by MunifTanjim** [comment]
Actually search was disabled on the demo site. Is should be enabled now.

**Comment by Fastidious** [comment]
@MunifTanjim that makes sense. Closing. Thanks!
