### ISSUE TITLE
How to add Language Switcher in Multilingual site?

### ISSUE THREAD

**Issue by solrayc** [MunifTanjim/minimo#205]
Hi Munif, thanks for your work, minimo theme is amazing, well optimized and blazing fast.
Can you please help me with multilingual mode in minimo?

I am trying to make my site multilingual, with language switch in main menu, just like on https://muniftanjim.com/ or like [here](https://regisphilibert.com/blog/2018/08/hugo-multilingual-part-1-managing-content-translation/), with language link that links to translated content in the same path. 

How do I make it work without manually setting menu parameters for each page by hand?

I have languages setup like this 
`[languages]

[languages.en]
lang = "en"
languageName = "English"
weight = 1

[languages.fr]
lang = "fr"
languageName = "French"
weight = 2`

With pages translated by filename, like so: 
/content/about.en.md
/content/about.fr.md

I have read everything I can find on this topic and still can't figure it out.

I would really appreciate your help, thanks.

Here is my config.toml:
https://gist.github.com/solrayc/818a37cc332e65bdbfd855ffbbbe1ae2

Hugo env
`Hugo Static Site Generator v0.53/extended windows/amd64 BuildDate: unknown
GOOS="windows"
GOARCH="amd64"
GOVERSION="go1.11.4`

**Comment by MunifTanjim** [comment]
Currently, it needs a bit of hacking to get the Language Switcher work.

Copy the **`/themes/minimo/layouts/partials/nav/menus/main.html`** to **`/layouts/partials/nav/menus/main.html`**. And add the following snippet in it:

```
{{- if gt ( len .Translations ) 0 -}}
  {{- range .Translations -}}
  <li class='item'>
    <a href='{{ .RelPermalink }}'>
      {{- .Language.LanguageName -}}
    </a>
  </li>
  {{- end -}}
{{- end -}}
```

The final file would be somewhat like this:

```
{{- if not .Site.Params.settings.hideMainMenu -}}

<nav id='main-menu' class='menu main-menu' aria-label='{{ i18n "mainMenu" }}'>
  <div class='container'>
    {{ partial "sidebar/toggler" . }}
    <ul>
    {{- range .Site.Menus.main -}}
      {{- $isCurrent := ( or ( $.IsMenuCurrent "main" . ) ( $.HasMenuCurrent "main" . ) ) -}}
      <li class='item {{- if $isCurrent }} current {{- end -}}'>
        <a {{ if $isCurrent -}} aria-current='page' {{ end -}} href='{{ .URL }}'>
          {{- .Name -}}
        </a>
      </li>
    {{- end -}}

    {{- if gt ( len .Translations ) 0 -}}
      {{- range .Translations -}}
      <li class='item'>
        <a href='{{ .RelPermalink }}'>
          {{- .Language.LanguageName -}}
        </a>
      </li>
      {{- end -}}
    {{- end -}}

    </ul>
  </div>
</nav>

{{- else -}}

{{ partial "sidebar/toggler" . }}

{{- end -}}
```

This is what I did on `muniftanjim.com`. This works alright for 2 alternating languages. If you have more than 2 languages, maybe you'll want a different approach.

And the `<link rel="alternate"` tag is automatically inserted, no need to do anything for that.

**Comment by solrayc** [comment]
Works like a charm! 

I tried it with 3 languages, default one + 2 additional ones, and it also works.

Appreciate your help, thanks! :)

**Comment by solrayc** [comment]
Tested it with the sidebar menu and it works too.

I added your code to ` layouts/partials/widgets/sidebar_menu.html ` , like so:

` {{- $defaultConfig := .Site.Data.config.default.widgets.sidebar_menu -}}
{{- $configData := ( or .Site.Data.config.widgets.sidebar_menu $defaultConfig ) -}}
{{- $lang := .Site.Language.Lang -}}
{{- $config := ( ( index $configData $lang ) | default $configData ) -}}

{{- $menu := ( $config.mirror | default "sidebar" ) -}}

{{- $.Scratch.Set "menu" $menu -}}

{{- $items := ( index .Site.Menus $menu ) -}}

{{- if $items -}}

<section class='widget widget-sidebar_menu sep-after'>
  {{- with $config.title -}}
  <header>
    <h4 class='title widget-title'>
      {{- . -}}
    </h4>
  </header>
  {{- end -}}

  <nav id='sidebar-menu' class='menu sidebar-menu' aria-label='{{ i18n "sidebarMenu" }}'>
    <div class='container'>
      <ul>
      {{- range $items -}}
        {{- template "menu_item" ( dict "Item" . "Page" $ ) -}}
      {{- end -}}

      {{- if gt ( len .Translations ) 0 -}}
      {{- range .Translations -}}
      <li class='item'>
        <a href='{{ .RelPermalink }}'>
          {{- .Language.LanguageName -}}
        </a>
      </li>
      {{- end -}}
    {{- end -}}



      </ul>
    </div>
  </nav>

</section>

{{- end -}}

{{- define "menu_item" -}}

{{- $menu := ( .Page.Scratch.Get "menu" ) -}}

{{- $isCurrent := ( .Page.IsMenuCurrent $menu .Item ) -}}
{{- $hasCurrent := ( .Page.HasMenuCurrent $menu .Item ) -}}
{{- $hasChildren := ( .Item.HasChildren ) -}}

<li class='item
  {{- if $hasChildren }} has-children {{- end -}}
  {{- if $hasCurrent }} has-current {{- end -}}
  {{- if $isCurrent }} current {{- end -}}
'>
  <a {{ if $isCurrent -}} aria-current='page' {{ end -}} href='{{ .Item.URL }}'>
    {{- .Item.Name -}}
  </a>

  {{- if $hasChildren -}}

  <button class='sub-menu-toggler'>
    <span class='screen-reader-text'>expand sub menu</span>
    <span class='sign'></span>
  </button>

  <ul class='sub-menu'>
  {{- range .Item.Children -}}
    {{- template "menu_item" ( dict "Item" . "Page" $.Page ) -}}
  {{- end -}}
  </ul>
  {{- end -}}

</li>

{{- end -}}
 `

Now I can change language from the sidebar.
