### ISSUE TITLE
support for Tipue Search

### ISSUE THREAD

**Issue by gour** [MunifTanjim/minimo#206]
Hello,

I have more luck with Fuse than with Lunr search, but when using Nikola static-site-generator, I was very happy with [Tipue Search](http://www.tipue.com/search/), so here I'm humbly proposing to consider adding support for it to the Minimo theme?

**Comment by MunifTanjim** [comment]
That is a **jQuery** plugin, so it won't be included in the theme repository. Sorry about that.

If you absolutely need it, you'll have to implement it yourself. You can take a look at the following files to get an idea about how to do that:

- https://github.com/MunifTanjim/minimo/tree/master/src/scripts/search
- https://github.com/MunifTanjim/minimo/blob/master/layouts/partials/widgets/search.html
- https://github.com/MunifTanjim/minimo/blob/master/layouts/page/search.html
- https://github.com/MunifTanjim/minimo/blob/master/layouts/page/search.json
