### ISSUE TITLE
Permission to use Telegram icon in hermit theme

### ISSUE THREAD

**Issue by detunized** [MunifTanjim/minimo#208]
I wanted to add the Telegram icon, that originally came from you theme, to https://github.com/Track3/hermit theme. Would that be OK? I created a PR https://github.com/Track3/hermit/pull/43 where the author said he/she would need your permission to merge. Could you please leave there a short comment, if you approve? Thanks a lot!

**Comment by MunifTanjim** [comment]
That icon is not even designed by me. It was added by @dmitrytrusov on #61.

Since Minimo uses the [MIT License](https://github.com/MunifTanjim/minimo/blob/master/LICENSE), I don't think he would mind.

So, just mention him in your PR and go ahead... :tada:

**Comment by detunized** [comment]
Thank, @MunifTanjim! I mentioned this in https://github.com/Track3/hermit/pull/45
