### ISSUE TITLE
Twitter card summary_large_image

### ISSUE THREAD

**Issue by druxstr** [MunifTanjim/minimo#209]
Hi, 

Is there a way to force a page to use the Twitter card [summary_large_image](https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/summary-card-with-large-image) instead of [summary](https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/summary) ? 

When you're not using a cover image, the default Twitter card is `summary`. 

So if you define an image in your front-matter, it's always displayed tiny on Twitter.

**Comment by MunifTanjim** [comment]
There are no built-in option for doing that.

You'll need to override this file:
https://github.com/MunifTanjim/minimo/blob/ce25eb1115642845ddd9e595f80134a0ec72b68b/layouts/partials/head/opengraph/twitter.html#L1

**Comment by singhkays** [comment]
@MunifTanjim For overriding, do you copy everything in the source file to the destination override file or just the 1st line above? Here's what I have in the override file now

```
<meta name='twitter:card' content='summary_large_image'>

{{- with .Site.Params.opengraph.twitter.page -}}
  <meta name='twitter:site' content='@{{- . -}}'>
{{- end -}}

{{- range $authorID := .Params.authors -}}
  {{- $author := ( index $.Site.Data.authors $authorID ) -}}
  {{- with $author.social.twitter -}}
    <meta name='twitter:creator' content='@{{- . -}}'>
  {{- end -}}
{{- end -}}

{{- with .Params.cover -}}
  {{- $type := ( printf "%T" . ) -}}
  {{- $isMap := ( not ( eq $type "string" ) ) -}}

  {{- $image := "" -}}
  {{- if $isMap -}}
    {{- $image = .image -}}
  {{- else -}}
    {{- $image = . -}}
  {{- end -}}'>

  {{- $image = ( replaceRE "^\\./" $.RelPermalink $image ) -}}

  <meta property='twitter:image' content='{{- $image | absURL -}}'>
  {{- if $isMap -}}
    {{- with .caption -}}
    <meta property='twitter:image:alt' content='{{ . | markdownify }}'>
    {{- end -}}
  {{- end -}}
{{- end -}}
```

**Comment by MunifTanjim** [comment]
> For overriding, do you copy everything in the source file to the destination override file or just the 1st line above?

You copy the whole thing and then change the parts you want.

> Here's what I have in the override file now @ /Blog/singhkays/layouts/partials/head/opengraph/twitter.html

Yeah, that should work.
