### ISSUE TITLE
Number of posts displayed with total posts in main menu

### ISSUE THREAD

**Issue by enricodata** [MunifTanjim/minimo#210]
Hi,

I would like to display the total number of posts beside the like to posts in the main menu.
However, I could not find where to modify the template of the main menu to add that.

I understood that I should add the following code ({{ len $items }})

How can we do that?

**Comment by MunifTanjim** [comment]
Need to override the [layouts/partials/nav/menus/main.html](https://github.com/MunifTanjim/minimo/blob/master/layouts/partials/nav/menus/main.html) template.

Example Guide for Template overriding: https://github.com/MunifTanjim/minimo/issues/272#issuecomment-617176128

You'll probably need to check the value of ` .URL ` and conditionally render the number of total posts. I think it'll be fairly complex.

Maybe people at https://discourse.gohugo.io/ can help?
