### ISSUE TITLE
Can the content be centered with the sidebar enabled?

### ISSUE THREAD

**Issue by singhkays** [MunifTanjim/minimo#216]
I like the sidebar but not the fact that the content moves off to a side. Can the content remain centered with the sidebar enabled?

**Comment by MunifTanjim** [comment]
It's not possible without some major stylesheet changes.

If you are familiar with CSS, you can try to tweak the stylesheets according to your needs. Otherwise, you'll have to find someone who can help you with that.

**Comment by singhkays** [comment]
@MunifTanjim I'm handy with CSS. If you let me know the files I should look into to alter the structure, I can try and figure it out. Also I saw there is a way to override widget defaults by creating data/config/widgets.toml file in my site root so config doesn't get overwritten on theme update. Would it be possible to do the same with this kind of modification?

**Comment by MunifTanjim** [comment]
> If you let me know the files I should look into to alter the structure, I can try and figure it out.

If you want to change the source files and compile the whole thing yourself, you'll probably find what you're looking for here: **[/src/stylesheets/layouts](https://github.com/MunifTanjim/minimo/tree/ee74eb139f6db19564909e9a5abe71ad67dfd88f/src/stylesheets/layouts)**

> Also I saw there is a way to override widget defaults by creating data/config/widgets.toml file in my site root so config doesn't get overwritten on theme update. Would it be possible to do the same with this kind of modification?

Of course. You'll have to use the `customCSS` option in your `config.toml` file:

https://github.com/MunifTanjim/minimo/blob/01a20d7f9b7f43c8eae667b49974ac6f2f0794d3/exampleSite/config.toml#L30

For example: if you set `customCSS = ["css/custom.css"]` and put a `custom.css` file in `/static/css` folder, it'll get included in your site automatically.

So, you can put your CSS overrides in that file.
