### ISSUE TITLE
TOC rendering to the left

### ISSUE THREAD

**Issue by singhkays** [MunifTanjim/minimo#217]
@Fastidious Override the **`/layouts/partials/entry/toc.html`** file with this:

```gohtml
{{ if eq .Params.toc true }}
<div class='entry-toc'>
  <div class='toc-title'>
    <span>
      {{- i18n "tableOfContents" -}}
    </span>
  </div>
  {{ .TableOfContents }}
</div>
{{ end }}
```

_Originally posted by @MunifTanjim in https://github.com/MunifTanjim/minimo/issues/63#issuecomment-350420820_

I followed the above code and created the override file structure at the root of my repo but I'm seeing the TOC being rendered to the left

![image](https://user-images.githubusercontent.com/6164178/56842948-b59a3c80-684f-11e9-8440-34b517b2f2ee.png)

![image](https://user-images.githubusercontent.com/6164178/56842952-c64ab280-684f-11e9-986b-c1da22f6ad99.png)

**Comment by MunifTanjim** [comment]
Try adding a `container` class to the `div.entry-toc` element:

```html
<div class='container entry-toc'>
```

**Comment by singhkays** [comment]
@MunifTanjim Thanks! That fixed the alignment but the styling seems off. Is it supposed to render like this? 

![image](https://user-images.githubusercontent.com/6164178/56853177-e5d9ed80-68d8-11e9-82b0-3cd2b5e4b485.png)

**Comment by MunifTanjim** [comment]
Somewhere along the way Hugo's Markdown renderer changed something, that's why the styling seems off.

Add this css somewhere to fix it:

```
.entry-toc ul ul {
  margin-left: 1em;
}
```

**Comment by singhkays** [comment]
@MunifTanjim I added that to custom.css but it didn't change the styling

![image](https://user-images.githubusercontent.com/6164178/56878904-2afe3c80-6a0b-11e9-87e8-ab309474c01f.png)

**Comment by MunifTanjim** [comment]
It should do what it's supposed to do. It will make nested headings add margin to their left. If you don't have nested headings, it won't change anything.
