### ISSUE TITLE
wrong opengraph url for relative path in frontmatter

### ISSUE THREAD

**Issue by singhkays** [MunifTanjim/minimo#218]
I followed the guide for opengraph and twitter configuration but I must be doing something wrong. Here's what I see in the Twitter card validator tool

![image](https://user-images.githubusercontent.com/6164178/56853416-4d456c80-68dc-11e9-8792-a46a0bde2b89.png)

Here's the URL in question https://www.singhkays.com/blog/detect-rolling-credits-video-indexer/

And here's how the article frontmatter is setup

```
---
categories:
- Azure
- Video Indexer
- Artificial Intelligence
- Video
tags:
- AI
- Azure
- Video Indexer
- Artificial Intelligence
title: 'Detect Rolling Credits with Azure Video Indexer'
date: 2019-04-11
draft: false
authors: ['singhkays']
images: ['media/netflix-autoplay.jpg']
---
```

And in config.toml
```
[params.opengraph.twitter]
page = "singhkays" # Twitter page username
```

**Comment by MunifTanjim** [comment]
Hugo has recently added a lots of new features. But Minimo hasn't been updated for a long time. So, some things are broken and not compatible with the latest Hugo versions.

This is what Minimo renders:
```html
<meta property="og:image" content="https://www.singhkays.com/media/netflix-autoplay.jpg">
```

This is what should be rendered in your case:
```html
<meta property="og:image" content="https://www.singhkays.com/blog/detect-rolling-credits-video-indexer/media/netflix-autoplay.jpg">
```

I can't say when I'm gonna get the time to fix these.

In the meantime, as a temporary fix, try adding this to your frontmatter:

```yaml
images: ['https://www.singhkays.com/blog/detect-rolling-credits-video-indexer/media/netflix-autoplay.jpg']
```

**Comment by MunifTanjim** [comment]
@singhkays should be fixed on latest commit.

**Comment by singhkays** [comment]
@MunifTanjim Fantastic!

**Comment by MunifTanjim** [comment]
@singhkays add `./` at the start if it's relative to the post directory.

So it should be:

```yml
images: ['./media/netflix-autoplay.jpg']
```

**Comment by singhkays** [comment]
Thanks! works now. Closing
