### ISSUE TITLE
Site title in the sidebar should link to the home page

### ISSUE THREAD

**Issue by jarekbryk** [MunifTanjim/minimo#219]
I think it would be beneficial to automatically link the site title in the sidebar to the home page (so `header h2` would link to the home page.

I have found the relevant bit of code (I think): in the `about.html`, code block starting in line 15:

    <h2 class='title site-title '>
    {{ with $config.title }}
      {{- . -}}
    {{ else }}
      {{- .Site.Title -}}
    {{ end }}
    </h2>

should be changed into:

    <h2 class='title site-title '>
    <a href='{{ $.Site.Home.RelPermalink }}'>
    {{ with $config.title }}
      {{- . -}}
    {{ else }}
      {{- .Site.Title -}}
    {{ end }}
    </a>
    </h2>

**Comment by MunifTanjim** [comment]
@jarekbryk do you want to create a PR?

**Comment by jarekbryk** [comment]
Will do, thanks!
