### ISSUE TITLE
Staticman comment system fails with submission error

### ISSUE THREAD

**Issue by lobopraveen** [MunifTanjim/minimo#220]
On a site with Staticman commenting enabled, all the comments fail with submission error.

Try the demo site - https://minimo.netlify.com/docs/comments-support/ 
Fill in the comment section and press the Comment! button.

Observed behavior:
> Yikes, Sorry!
> Error occured. Couldn't submit your comment. Please try again. Thank You!

Also, the Staticman support in minimo is missing the reCAPTCHA implementation _I think_. See https://github.com/eduardoboucas/staticman-recaptcha#staticman--recaptcha

**Comment by MunifTanjim** [comment]
> Try the demo site - https://minimo.netlify.com/docs/comments-support/

It is expected to fail. It's not enabled on the demo site.

**Comment by lobopraveen** [comment]
I just gave the demo site as an example without knowing it is not enabled
there.

I have it enabled on my site - praveenlobo.com . I tested it when I set it
up and it had worked as you can see from the comments on the first post.
However, It has stopped working and I get the same error as I get on the
demo site.

I don't remember testing it after enabling the reCAPTCHA. Maybe that's when
it stopped working. I will disable it and see if commenting works again.

**Comment by MunifTanjim** [comment]
> I don't remember testing it after enabling the reCAPTCHA.

reCAPTCHA support is definitely not implemented in Minimo. If you need that, you'll have to override the [/layouts/partials/comments/staticman/form.html](https://github.com/MunifTanjim/minimo/blob/a5c3faefcadc2bf06299d206e6de1bef6dd520a0/layouts/partials/comments/staticman/form.html). You'll probably need to change the javascript file too, I'm not sure about that.

**Comment by VincentTam** [comment]
> reCAPTCHA support is definitely not implemented in Minimo

Many themes support reCAPTCHA, like Beautiful Hugo/Jekyll, Minimal Mistakes,etc.  reCAPTCHA is a popular service that is easy to implement, despite inaccessible for some VPN users and considered as evil to haters of Google.

Due to Staticman's spam problem reported in eduardoboucas/staticman#175 and eduardoboucas/staticman#298, there's a genuine need for reCAPTCHA integration in this theme.
