### ISSUE TITLE
Category names with more than one word not displayed

### ISSUE THREAD

**Issue by Guillawme** [MunifTanjim/minimo#223]
As of commit 5647258, if a category name is made of more than two words, it is not displayed anymore at the right of the folder icon (the icon itself is displayed correctly) at the bottom of a blog post. Category names made of a single word are displayed normally.

Here are some examples:

- https://www.gaullier.org/en/blog/2018/12/10/new-publication/ : a single-word category name displayed correctly;
- https://www.gaullier.org/en/blog/2018/12/11/figure-2-zhou-et-al-2018/ : a two-word category name not displayed at all;
- https://www.gaullier.org/en/blog/2018/12/15/keeping-up-with-nucleosome-structures/ : a four-word category name not displayed at all.

This behavior appeared after commit e025d0d, the version of Minimo I last built my website with and that displayed category names correctly. I also updated Hugo between these two builds of my website, so this could be the reason as well, although Hugo did not report any problem when it built the site.

I tried to enclose the multi-word category name in single quotes in the post's front matter, but it did not solve the problem.
Because these category names do not need a translation, I don't have any file in `content/categories/<mutli_word_category>/_index.<lang>.md`. I haven't tested whether defining a title for these categories would fix the problem.

**Comment by MunifTanjim** [comment]
Check if the latest commit fixes it.

**Comment by Guillawme** [comment]
Looks like it worked, thank you. 👍
