### ISSUE TITLE
enabling fuse.js search

### ISSUE THREAD

**Issue by ibecav** [MunifTanjim/minimo#227]
Hi,

Thanks for the wonderful theme.  I did a default install and all seems to be working except search.  My config.toml has 

```
[params.search]
client = "fuse"
```
in it.  I have the default searchbar widget there.  Doco says to make a page `/content/page/search.md` I don't have a `/page/` subdirectory but if I create one and then add the page there it becomes the new index page for my site????

FWIW the site is https://ibecav.netlify.com/

**Comment by MunifTanjim** [comment]
The search seems to be working: https://ibecav.netlify.com/search/?q=mac

Why do you think it's not working?

**Comment by ibecav** [comment]
Sorry I kept playing around and creating a file `/content/search.md` instead of `/content/page/search.md` seems to have solved it for me

**Comment by ibecav** [comment]
I'm going to close this since it now works for me.  Not sure whether yould adjust your documentation or I'm a fluke case?
