### ISSUE TITLE
Images in menu items?

### ISSUE THREAD

**Issue by ibecav** [MunifTanjim/minimo#228]
Hi I'd like to know whether the theme could support small mages as part of it's templates.

See https://ibecav.netlify.com/ for an example.  IN this case I manually added the <img> tags in index.html

`  <a href='https://www.r-bloggers.com/'><img src='/images/rblogger.png' width="42" height="42"></a></li><li class='item'>
`
I tried fiddling with the `pre` tag in `[[menu.sidebar]]` in `config.toml` but couldn't get it to pass through?

**Comment by MunifTanjim** [comment]
@ibecav Sorry for the late response.

I've added support for the `pre` and `post` options for the menus.

Can you try with the latest commit #9759f77 and see if it works for you?

**Comment by solrayc** [comment]
That did not work for me. 

Tried in sidebar and main menu, with both `pre `and `post `options.

Site is generated without errors.
The menu items get created, but `<img src='' /> ` doesn't show up in the page source.

The theme is up to date.

Hugo version:

```
Hugo Static Site Generator v0.55.6/extended windows/amd64 BuildDate: unknown
GOOS="windows"
GOARCH="amd64"
GOVERSION="go1.12.2"
```

**Comment by MunifTanjim** [comment]
@solrayc Can you show me a repository with the problem? I just checked the theme and `pre` and `post` options are working as intended on `Hugo Static Site Generator v0.55.6 linux/amd64 BuildDate: 2019-05-18T11:36:07Z`
