### ISSUE TITLE
Providing accent color in Search Bar Focus

### ISSUE THREAD

**Issue by ammo0110** [MunifTanjim/minimo#229]
Currently, we can choose the accent color of the theme using "accentColor" property in "params.settings"(config.toml)

However, instead of showing this accent color, the search bar widget shows the default yellow color "#ffcd00" when it is in focus.

**Comment by MunifTanjim** [comment]
@ammo0110 Try the latest commit

**Comment by ammo0110** [comment]
It's working. Thanks a lot! :)
