### ISSUE TITLE
Add email slot

### ISSUE THREAD

**Issue by sourabhtk37** [MunifTanjim/minimo#23]
How do I add email slots, is there svg icon for the same?

**Comment by MunifTanjim** [comment]
What do you mean by email slot? An email icon in the footer?

**Comment by sourabhtk37** [comment]
Yeah exactly. In `config.toml` I can input links for github, facebook and other social profiles. Is there something for adding email?

**Comment by MunifTanjim** [comment]
Added it in the latest commit.

**Comment by sourabhtk37** [comment]
Thank you so much.
Please let me know in what ways I can contribute to `minimo`.

**Comment by MunifTanjim** [comment]
Thanks for you interest. :smiley:
Well, Minimo is a very small project. So there isn't much to contribute, other than fixing small bugs and giving feedback.
