### ISSUE TITLE
Taxonomy do not appears in the bottom of page if not english

### ISSUE THREAD

**Issue by abonec** [MunifTanjim/minimo#230]
If I assign non english tags for my posts it is not appear in the bottom of the post.
![image](https://user-images.githubusercontent.com/240587/58072285-e1d37f80-7ba7-11e9-94c5-a61a180b01ab.png)
Tags for example:
tags: ["тег на русском", "english tag"]

**Comment by MunifTanjim** [comment]
@abonec Try the latest commit

**Comment by abonec** [comment]
Works, thx
