### ISSUE TITLE
Implementing Mermaid Library

### ISSUE THREAD

**Issue by ammo0110** [MunifTanjim/minimo#231]
Hi!

[Mermaid](https://mermaidjs.github.io/) is a JS library which lets you to generate diagram and flowcharts from text, in a similar manner as Markdown.

It can be used to generate flowcharts, sequence diagrams and gantt charts from text.

I was wondering if mermaid can be integrated into minimo theme without much hassle.

Currently, it is implemented in [hugo learn theme](https://themes.gohugo.io//theme/hugo-theme-learn/en/shortcodes/mermaid/) with hugo shortcodes.

Finally, kudos for building such a feature rich and polished theme!

**Comment by ammo0110** [comment]
Hi!

I have integrated mermaid. I can open a Pull Request if you would like.

**Comment by MunifTanjim** [comment]
Yeah, of course! :smiley:

**Comment by ammo0110** [comment]
I have opened the pull request #235
