### ISSUE TITLE
Inconsistent line breaks in post titles

### ISSUE THREAD

**Issue by lashoun** [MunifTanjim/minimo#234]
Hi MunifTanjim, thanks for your wonderful work on this theme, I love it!

However, I'm having trouble fixing an issue with inconsistent line breaks in post titles. If you look at these two images, you'll see what I mean.
 
https://i.imgur.com/Gmr3i63.png
https://i.imgur.com/qa4FfMs.png

Although in the second one the title is longer than in the first, the line break always occurs before the last word. I'd like to remove the line break but I don't know what to do... Do you have any idea?

**Comment by MunifTanjim** [comment]
Hey @lashoun, thanks for reporting this.

I've pushed a fix on https://github.com/MunifTanjim/minimo/commit/698f5f8a4d8d64ebd678c2253080212c86153a65. Can you check now?

**Comment by lashoun** [comment]
That worked perfectly. Thanks, and kudos for the reaction time!
