### ISSUE TITLE
Double input of a Staticman parameter

### ISSUE THREAD

**Issue by VincentTam** [MunifTanjim/minimo#237]
In #224, Hugo's cache has been introduced so that user only needs to input reCAPTCHA parameters only once in the Staticman config file.

https://github.com/MunifTanjim/minimo/blob/d2587aafcbe24f66a3bfdba225da0c83334e2515/layouts/partials/comments/staticman/form.html#L12

Nonetheless, users have to input the `branch` twice, once in the theme config file and once in the Staticman config file.  A little line like

```go
{{- $branch := $staticman.comments.branch -}}
```

would make the whole thing consistent with your arguments for calling parameters from the Staticman config file.

**Comment by MunifTanjim** [comment]
@VincentTam check the latest commit: 4eb4160c94dd2f85fc8a10fb7d220127252a11d8

**Comment by VincentTam** [comment]
Thanks for commit.
