### ISSUE TITLE
Is there any way to extend the social.base table without generating a warning?

### ISSUE THREAD

**Issue by techxplorer** [MunifTanjim/minimo#238]
Hi,

In my website I've added some social icons. In doing so I needed to create my own `data/theme.toml` file to add entries to the social.base table. 

No when I build my website I see the following warning:

```
Data for key 'social' in path 'minimo/theme.toml' is overridden by higher precedence data already in the data tree
```

Is there any way that we could work to address this? I considered removing the ` minimo/data/theme.toml` file, but would prefer not to in order to keep the submodule clean. 

Any thoughts you have are most welcome.

**Comment by MunifTanjim** [comment]
You are doing it the right way. No need to do anything differently.

The warning should be fixed in the upcoming Hugo version:  https://github.com/gohugoio/hugo/pull/6049#issuecomment-504027923

**Comment by techxplorer** [comment]
Hi @MunifTanjim,

Thanks you for this theme and for being so responsive. I'll keep an eye out for a fix in a future release of Hugo.
