### ISSUE TITLE
404 when using search

### ISSUE THREAD

**Issue by ghost** [MunifTanjim/minimo#240]
Hi, whenever I use search on the rendered page, it jumps to a new page that says 404 page not found...

I used the config.toml from your website, didn't change anything, but search just doesn't work. The url become something like localhost:1313/search/?q=blablabla.

**Comment by MunifTanjim** [comment]
@ylmx Have you created a Search page like the exampleSite? https://github.com/MunifTanjim/minimo/blob/998aad0a0f8707e90ed8ff769a681b7fe0aa9fcf/exampleSite/content/page/search.md

**Comment by immanuelfodor** [comment]
Ran into the same issue lately, I can confirm that creating the search file at `/content/page/search.md` as linked above solves the problem.
