### ISSUE TITLE
some warning in the lastest hugo 

### ISSUE THREAD

**Issue by hwdef** [MunifTanjim/minimo#243]
![warningimage](https://user-images.githubusercontent.com/13084946/64245879-5d322480-cf3e-11e9-8649-f7b0533c78f6.png)

**Comment by hwdef** [comment]
@MunifTanjim

**Comment by MunifTanjim** [comment]
Seems like you're using a previous version of Minimo. Those were fixed long ago in: https://github.com/MunifTanjim/minimo/commit/d9ccf2ec3d0f0e5c63d7913b704ecc800ebac445 & https://github.com/MunifTanjim/minimo/commit/c8967699cc68d3e3ccf7981e6b224ab910c198d9

**Comment by hwdef** [comment]
please update the release file.

**Comment by MunifTanjim** [comment]
@hwdef  [v2.8.0](https://github.com/MunifTanjim/minimo/releases/tag/v2.8.0)

**Comment by hwdef** [comment]
@MunifTanjim 
Thank you very much
