### ISSUE TITLE
what about add a abundant footter?

### ISSUE THREAD

**Issue by idevz** [MunifTanjim/minimo#250]
like the title, what about add a  abundant footter?
here is a [example](http://jolestar.com):
<img width="816" alt="Screen Shot 2019-10-23 at 4 21 13 PM" src="https://user-images.githubusercontent.com/2113827/67382048-71e67c80-f5bf-11e9-8c88-38047d7c38af.png">
at least if we have a QR code putting place?

**Comment by MunifTanjim** [comment]
You can always override the partial: `layouts/partials/footer.html`

**Comment by idevz** [comment]
thanks @MunifTanjim , but I have know nothing about stylesheets nor scss .
now I just update the content.html and add a pic for every page.
<img width="778" alt="Screen Shot 2019-10-23 at 9 08 54 PM" src="https://user-images.githubusercontent.com/2113827/67396184-b67f1180-f5d9-11e9-8f1d-52decade8836.png">
