### ISSUE TITLE
Update 2.1.1 -> 2.1.2: serialize-javascript vulnerability found in …/minimo/package-lock.json

### ISSUE THREAD

**Issue by cgpu** [MunifTanjim/minimo#255]
Hi,

While checking the theme I had an alert from `dependabot` for a dependency when I submitted. Feel free to take a look and update the version after the patch. 

![image](https://user-images.githubusercontent.com/38183826/72397484-ee5ca780-3737-11ea-86cf-55f783877df9.png)

I have attached the report as pdf below:

[alerts-serialize.pdf](https://github.com/MunifTanjim/minimo/files/4062620/alerts-serialize.pdf)

**Comment by MunifTanjim** [comment]
It's in devDependencies and does not affect the output.
