### ISSUE TITLE
sidebar-toggler overlaps breadcrumbs when hideMainMenu is enabled and sidebar is open on mobile

### ISSUE THREAD

**Issue by hwustrack** [MunifTanjim/minimo#256]
sidebar-toggler overlaps breadcrumbs when hideMainMenu is enabled and sidebar is open on mobile

![SidebarClosed](https://user-images.githubusercontent.com/15225112/72581185-54694a80-3943-11ea-9546-898a7b672052.png)

![SidebarOpen](https://user-images.githubusercontent.com/15225112/72581287-b5911e00-3943-11ea-8faf-710d325a6564.png)

I can share a repro if that's helpful and happy to submit a fix.

**Comment by MunifTanjim** [comment]
Please go ahead and create a PR... that would be great 😃

**Comment by hwustrack** [comment]
Sure, I’ll get to work on it!
