### ISSUE TITLE
anchorize breaks some tags

### ISSUE THREAD

**Issue by madhead** [MunifTanjim/minimo#260]
I have a tag with a slash in my blog: `kotlin/native`. `preserveTaxonomyNames` config parameter is`true`. I noticed, that it is not rendered in content pages correctly (note that gap between commas):

<img width="363" alt="image" src="https://user-images.githubusercontent.com/577360/75265672-4a6c1e80-5802-11ea-9823-04fb051e2cb5.png">

However the tag page lists all the articles:

<img width="509" alt="image" src="https://user-images.githubusercontent.com/577360/75265751-653e9300-5802-11ea-810d-a0979e1ef0fb.png">

I tried to remove the `anchorize` function in `taxonomy-list.html` partial:

https://github.com/MunifTanjim/minimo/blob/ef9288460e3e6eb0ecb03556d5b26a4c8da0cd51/layouts/partials/entry/taxonomy-list.html#L11

And it seems to help:

<img width="450" alt="image" src="https://user-images.githubusercontent.com/577360/75265852-8a330600-5802-11ea-9af2-ce7ba600d950.png">

Why is it needed here? Is it safe to remove it?

**Comment by MunifTanjim** [comment]
Fixed all of #230, #260, #264 together.

As a side-effect, now minimum Hugo version required is: `0.65`

**Comment by madhead** [comment]
Thank you!
