### ISSUE TITLE
Social menu not displayed in Firefox

### ISSUE THREAD

**Issue by Guillawme** [MunifTanjim/minimo#261]
Hello,

I just noticed that the social menu is not displayed anymore on my website. After a while getting confused at the situation, I realized that the site is built properly because "view source" in Firefox shows the social menu's code. Here are a few facts about this strange bug:

- my website is built with the latest Minimo 398845c1 and I only have very minimal [custom CSS](https://framagit.org/Guillawme/gaullier.org/-/blob/master/static/css/custom.css) unrelated to the social menu widget
- the social menu is both in the sidebar and in the footer, its code appears in "view source" but the widget is not displayed in Firefox 73.0.1
- the social menu is displayed properly in Safari both on macOS and iOS (both at their newest versions as of this writing)
- just by testing all browsers I have at hand, I noticed that the social menu is also displayed correctly in Tor Browser 9.0.5 (based on Firefox 68.5.0esr), suggesting that the bug is specific to recent versions of Firefox

To reproduce this bug, open https://www.gaullier.org/en/ in different browsers and check whether you see the social menu in the sidebar and footer. Expected result: the social menu should be displayed. Actual result: varies depending on browser.

**Comment by Guillawme** [comment]
Well, it looks like this was caused by Hugo after all. I just upgraded Hugo from 0.65.3 to 0.66.0 this morning, and now I see the social menu in Firefox (same version as yesterday).

**Comment by Guillawme** [comment]
This is even weirder than I thought. The social menu is still not displayed after rebuilding with newest Hugo, but this is only in one Firefox profile. The social menu was always displayed fine in my other (work) Firefox profile. These two profiles have different sets of extensions, so I don't think I can easily figure out what's going on.

**Comment by MunifTanjim** [comment]
I can see it just fine on Firefox. Maybe your extensions are blocking something...

**Comment by Guillawme** [comment]
Yes, I could see it in one profile and not in another, so this must be specific to a profile. This is why I closed the issue myself. Sorry for the false alarm.
