### ISSUE TITLE
Firefox doesn't display social_menu widget

### ISSUE THREAD

**Issue by immanuelfodor** [MunifTanjim/minimo#262]
Hi, first of all, thanks for creating this awesome Hugo theme!

I've started setting up the theme and quickly ran into a problem, the `social_menu` widget is not displayed under FF latest version, but it is in Chrome. How can it be?

If I remove the `widget-social_menu` class in FF, the icons appear as an unformatted list, so I think it must be something with that. 

![image](https://user-images.githubusercontent.com/21174107/76392006-05eb9180-6371-11ea-85a8-f956b5ac9155.png)

![image](https://user-images.githubusercontent.com/21174107/76392966-de95c400-6372-11ea-9914-38ff39af5525.png)

The same happens if I add the widget to the sidebar, the last separator is displayed as if there is something but nothing is visible.

![image](https://user-images.githubusercontent.com/21174107/76392765-8363d180-6372-11ea-941a-0c1e5d5efb18.png)

There is no `display:none` or anything like that in the styles on the node, I don't get it why it's greyed out:

![image](https://user-images.githubusercontent.com/21174107/76393077-17359d80-6373-11ea-8c07-b01025894e6f.png)

I didn't add any custom CSS nor JS to the Hugo project, just started to fiddle with the `config.toml`.

The strangest thing that it works fine under the official demo with FF: https://minimo.netlify.com

My theme submodule is at 398845c1 and I'm using Hugo 0.67.0, FF version is:

![image](https://user-images.githubusercontent.com/21174107/76393241-70053600-6373-11ea-91a3-3046730bddbb.png)

Do you have any idea or debug ideas why this could happen to me?

**Comment by MunifTanjim** [comment]
Can you give me a live example? or access to a repository with reproducible bug?

**Comment by immanuelfodor** [comment]
Okay, here it is:

https://keybase.io/muniftanjim

```
-----BEGIN PGP MESSAGE-----

wcFMA+pCYVfmpoUFAQ/9FmYtRawA/CiCKodm7gZF3l64IHNRvp2P90oSRGVb
Wdb9e1AvP05cKOYRrdxnSRarNqtBXvqK8VmFDPYC6MvPJ0Jk004dhnyN++gx
FVJdWqmwuWuuZj/Ra0fvjp9bsC/4WXiTDf+YpEdxt6MId3/DRdysxWBLDpO0
B8B/6sohKNTSVkE+f5uGHI+tBN7T2GvmL2Dw4Z0kcgzU9ZZSqON/0TDNQ0Cs
wg/ZvFQNIzrWV/s848uRhfM3JtGgokPqwL4krdv24I1VnLIPVWbMMqRbKb/6
ABCGU118j1tph06zLjMaNyxQ/HQcPOvNWifg3xywddNxz3YPu+Kk2UEO7O5P
GEwPel7vAvKx2Qs/8DXigyw9GEqMOFdcEipoTveBjOVggV19uHrjqh/O1lyn
jky1eX08Yf/QxHQQXwSwngX6V7SrqkbVx2eXhC9DKRMdrU6fMAX/cnW8W5xD
HrrOrO1lrh6Wy6ubz3o/4MeYA/E39O6hn/FMISq2uxRzq6lUqJmT6brw3T9z
dEgwyBgMT6CoZzprHQwfJ7E9RFgg51qxLhvzLsZtQKiOz45uspqnlvWrp1C7
HD3op4cJKfTj0kZ+z5sG/1YOjgkwRYDIkqXim+4tVQsCBtqOmt495L2xtfp/
hXUnep8oLW2izdrOhFqxmaImeV5LbTurN2foey/ImM3BwUwDwhl4Udp1xsUB
EACldaBeH5l7nJrLwNqQISxYGHuZ9KtS38X+8ICTbs1izuAn8KNjB60NSWZb
/ocZzc1lSPwdts1xPr8kbsjvY742XaqJa2rYrgcC5CPT8XJN3P0lKtMkBlRC
dWS1+VifhCAWQbqAfVfbI76yX+NPBFj+rUguxoAfdX0LsjE0U/+NcdzavmTJ
yEjjwpRiA2NEq15Zu3/+JMUT8yL58yTqqKY7SGONe3r7GJDlmcYtF7dqIY+o
Gwzd3F4o+J5dhgp085ccWQvXXUYbDxRKclZnyCfYWMxdpWJaasoZTICvtfH9
SLdqjiF9Jy3QprryoaDY7lW8ZHSK4YJ4ll30lsZaab6U9iO48cjdA1acRUZm
6gQCGs1iMqhVVWwXNXrqpruLKK5P8VsWKm/5C1z2sOiNs2/fRmREslUNF5Nt
G7s1fXxki/RPwlshJnBxcQREF25n3DVqvvO8fMdyPecZAe40FoWtzOn8wPMu
AT9Dob2pT6bS2p5Gf+2j1Irrnz2mfsTJKt1CYWva1Xvidzo36btm9DIHc8DH
N27jEsY6j/NG9ulM1uqQcTEz7iwhzm9kbpeiFbscB9bnAmfO08P8S8zaUcb7
yybGdi3+XzqPCpFGypJQlO3UdEjgKUEGPgpJDzreiGQt9PodNzJNpf6RXiOs
boZb2svn3C14EKlP+lDsV4Xxw9J9AZ+eFEpmUiMVN0pDiKQY+UeN02MvGWJt
5ruDD9BPktW8CQWYvG2QEQ2j91HWt5IPFrhtnmEG9IJ6PR4ymOrk0t2Qpiav
FwMwFhEa8KkNubyWORITJe7UCB1bM8cNX+5ncEUZL7JN9IGt5Wl6nWwiEED+
o7hB9rPfcRNU1y0=
=0YSU
-----END PGP MESSAGE-----
```

**Comment by MunifTanjim** [comment]
:thinking: I can see them in both places using Firefox: 

![image](https://user-images.githubusercontent.com/8050659/76451266-63c3bc00-63f9-11ea-9493-8337076bc12a.png)

Maybe you're using some Firefox extension that's causing the problem? (this happened on #261)

**Comment by immanuelfodor** [comment]
Hmm, weird, then why it works with the same extensions on the demo site? 🤔

**Comment by immanuelfodor** [comment]
I'll try to create a copy of the social widget html and replace the social word with something else, then copy the social widget CSS rules to the custom css file with the adjusted class name. If it's blocked by an adblocker cosmetic rule for the social word, it should skip it then.

**Comment by immanuelfodor** [comment]
I couldn't wait for tomorrow, did the class change, and now it's displayed at both places. Before that, I tried disabling uBlock Origin, and it also showed up, this is why I implemented it even if it's late 😃 Thanks for the help, I wouldn't think of an extension doing it otherwise. I suggest changing the "social" word for something obscure later to circumvent this issue for others, too.
