### ISSUE TITLE
How could I change the width of the theme?

### ISSUE THREAD

**Issue by LiangqinRen** [MunifTanjim/minimo#267]
Thanks for this beautiful theme! But I have two questions.
At first, this theme looked appropriate at mobile phones, but it seemed too narrow at PC. I mean, it only takes the left half of the screen, I want it to use more space.
Second, how can I set an overall count of articles? I use this theme for blog, accurately, for Leetcode solutions, I hope there will be a list of all articles and a total count.

**Comment by MunifTanjim** [comment]
> At first, this theme looked appropriate at mobile phones, but it seemed too narrow at PC. I mean, it only takes the left half of the screen, I want it to use more space.

Follow this comment to use the `customCSS` option: https://github.com/MunifTanjim/minimo/issues/64#issuecomment-349304677

Then add something like this in your custom css file:

```css
.container {
  max-width: 920px;
}
```

> Second, how can I set an overall count of articles?

If you mean that you want to control the post count on each page, then

https://github.com/MunifTanjim/minimo/blob/66c81171f07ab2c7e78e54a8e0a97d48d66db2b6/exampleSite/config.toml#L11

Use the `paginate` option in your `config.toml` file.

> I hope there will be a list of all articles and a total count.

If you want to add a page with all your posts together, see this comment: https://github.com/MunifTanjim/minimo/issues/95#issuecomment-364777002

**Comment by LiangqinRen** [comment]
Thank you for your reply!
I have changed the width, which is most important, and article numbers on the same page. But I can't understand your third comment, but that's ok for now, I don't have that much articles at present.
Again, thanks for your valueable instructions.
