### ISSUE TITLE
[Template Override] Additional string field under title in posts - after reading time field

### ISSUE THREAD

**Issue by lbartnicki92** [MunifTanjim/minimo#272]
Hi!
Is there any option(I can't find in docs) to add near "Reading Time" in posts additional field - I'm writing blog about DBA and DevOps topics - something like notes/technical procedures - It will be superb to have there field with software version that post is about 🙂For example post about Docker Volumes: Title, under it name of writer, reading time and label Docker 19.03

**Comment by MunifTanjim** [comment]
You need to follow these steps:

- Override Minimo's [layouts/partials/entry/meta.html]( https://github.com/MunifTanjim/minimo/blob/d2e08a130ffecfe1f8ea0d09ac123c7e060e3cd1/layouts/partials/entry/meta.html) file, by creating the following file in your repo:

**`/layouts/partials/entry/meta.html`**
```html
{{- $defaultConfig := slice "page" -}}
{{- $config := .Site.Params.settings.hideEntryMeta | default $defaultConfig -}}
{{- $configType := ( printf "%T" $config ) -}}

{{- if ( eq $configType "bool" ) -}}
  {{- $.Scratch.Set "showEntryMeta" ( not $config ) -}}
{{- else -}}
  {{- $.Scratch.Set "showEntryMeta" ( not ( in $config .Section ) ) -}}
{{- end -}}

{{- if ( $.Scratch.Get "showEntryMeta" ) -}}
<div class='entry-meta'>
  {{ partial "entry/meta/posted-on" . }}
  {{ partial "entry/meta/author" . }}
  {{ partial "entry/meta/reading-time" . }}
  {{ partial "entry/meta/label" . }}
</div>
{{ end }}
```

_[ Note: we just added this line: `{{ partial "entry/meta/label" . }}` ]_

- Add the `entry/meta/label` partial template by creating the following file in your repo:

**`/layouts/partials/entry/meta/label.html`**
```html
{{- with .Params.label -}}

<span class='entry-label'>
  <span>Label: </span> {{ . }}
</span>

{{- end -}}
```

- Now in your content markdown files, you can do this:

```
---
label: "Docker 19.03"
---
```

That should do what you want.

This is how template overriding works in Hugo. You can override [any template files](https://github.com/MunifTanjim/minimo/tree/d2e08a130ffecfe1f8ea0d09ac123c7e060e3cd1/layouts) Minimo uses. So, you can add/remove other stuffs too in various places of the template.

Or if you don't wanna go through all these trouble, you can just use the built-in `tags` support:
```

---
tags:
  - "Docker"
  - "Docker 19.03"
```

But this will show them under the post content.

**Comment by lbartnicki92** [comment]
It's works! 
Thank you very much :)
