### ISSUE TITLE
Sort by title in the Series.

### ISSUE THREAD

**Issue by LiangqinRen** [MunifTanjim/minimo#275]
Hi!
Can I sort articles in Series by title? Now, it sorts articles by time. I use this theme to record my solutions for Leetcode, while my article's title looks like '1. Two Sums'. So, I hope I could sort the article by the title, that's means, by its number.
Thank you very much.

**Comment by MunifTanjim** [comment]
I believe you can do so by overriding the `layouts/_default/list.html` file's this line:

https://github.com/MunifTanjim/minimo/blob/cdb10ca404f2ea43be7afa600e93235c323d7976/layouts/_default/list.html#L13

with this:

```go
    {{ range ( .Paginate .Pages.ByTitle ).Pages }}
```

To get an idea about how to override template files, see this: https://github.com/MunifTanjim/minimo/issues/272#issuecomment-617176128

**Comment by LiangqinRen** [comment]
> I believe you can do so by overriding the [`layouts/_default/list.html`](https://github.com/MunifTanjim/minimo/blob/cdb10ca404f2ea43be7afa600e93235c323d7976/layouts/_default/list.html) file's this line:
> 
> https://github.com/MunifTanjim/minimo/blob/cdb10ca404f2ea43be7afa600e93235c323d7976/layouts/_default/list.html#L13
> 
> with this:
> 
> ```go
>     {{ range ( .Paginate .Pages.ByTitle ).Pages }}
> ```
> 
> To get an idea about how to override template files, see this: [#272 (comment)](https://github.com/MunifTanjim/minimo/issues/272#issuecomment-617176128)
> 
> _**TLDR**: Basically you'll just create a file `layouts/_default/list.html` on your repository's root with the modified template._

Thanks for your reply.
But I'm sorry, It doesn't work. As your instrucment, I modify that line in 'list.html' and copy this file to 'layouts/_default', which used to be an empty folder. But it doesn't work. Then, I copy other html files in the same folder to my website, and it doesn't work as well.
I don't familiar with the hugo theme and the front-end, so could you give me more instructions?

**Comment by MunifTanjim** [comment]
Can you show me the repository for your site? I can help you if I don't have enough information.

**Comment by LiangqinRen** [comment]
> Can you show me the repository for your site? I can help you if I don't have enough information.

https://github.com/LiangqinRen/Algorithm
This is my repository's link. Thank you very much.

**Comment by MunifTanjim** [comment]
I don't see the `layouts/_default/list.html` file in there :thinking: @LiangqinRen

**Comment by LiangqinRen** [comment]
> I don't see the `layouts/_default/list.html` file in there 🤔 @LiangqinRen

I'm sorry, I changed it on my computer, butI forget to push it.
Now, I have pushed it.

**Comment by MunifTanjim** [comment]
You have a syntax error here: https://github.com/LiangqinRen/Algorithm/blob/a8127d39ec868000766e0aad8d85a70363ddb4d8/layouts/_default/list.html#L13

`{{ range ( .Paginate.Pages.ByTitle ).Pages }}`
should be
`{{ range ( .Paginate .Pages.ByTitle ).Pages }}`

Notice the <space> after `.Paginate`

Also, because of how the order by title is done, you need to prefix the numbers in your title with `0`.

For example: `5. Five` will come after `15. Fifteen` by default. To get your expected order, you need to have `05. Five` and `15. Fifteen`.

**Comment by LiangqinRen** [comment]
Thanks for your patience, and I was preparing for TOFEL tests to apply for a Ph.D. in the U.S., so I didn't reply for your help.
And I finally find the solution.
I occasionally find the link 'https://blog.pytool.com/language/golang/hugo/hugo-template-function-sort/', which talks about the sorting of Hugo(in Chinese). It says that we can sort the file by date like this
'''
{{ range .Data.Pages.ByDate }}

{{ end }}
'''
So, I search this code in the project, and find it locates at the file 'themes/minimo/layouts/taxonomy/series.html'. Then, I sort files by title, it works but as you say, I have to add some zero at the title, which is ugly in my opinion.
Then, I notice that the user could sort files by other information, so I try to sort files by weight, which means 'range .Data.Pages.ByWeight' and add weight to every file. 
After this, it works!  Without this little problem, I think this theme is the best!
