### ISSUE TITLE
Changing the logo

### ISSUE THREAD

**Issue by edoreld** [MunifTanjim/minimo#280]
Hello,

I just started using this theme for my personal blog. It's very nice!

I wonder if there exists an option to change the logo. I looked through the documentation but I couldn't find anything. I think it would be super neat.

**Comment by MunifTanjim** [comment]
Please take a look at the "Widget: About"

https://minimo.netlify.app/docs/widgets/#widget-configuration-options

**Comment by edoreld** [comment]
Thank you, I managed to make it work. 

At first I put my image under `<project-root>/images` but then I realized I was supposed to put it into the `<project-root>/content/images` directory instead.
