### ISSUE TITLE
Hugo 0.73.0 broke things

### ISSUE THREAD

**Issue by Guillawme** [MunifTanjim/minimo#285]
Hello,

Apologies if you already noticed this.

My site using Minimo builds fine with Hugo up to version 0.72.0. Building it fails since Hugo 0.73.0 (I also just tested with 0.74.1 and it also fails, I haven't tested with 0.74.0).

If I understand the error messages correctly, it looks like [this change](https://github.com/gohugoio/hugo/issues/6911) (Rename taxonomy kinds from taxonomy to term, taxonomyTerm to taxonomy) that got merged in Hugo 0.73.0 is what causes the problem.

Not a big deal, I kept Hugo 0.72.0 around and will build with this version until Minimo is compatible with current Hugo.

Cheers.

**Comment by MunifTanjim** [comment]
Thanks for letting me know this. :smiley: 

I'll update it as soon as I can.

**Comment by MunifTanjim** [comment]
Hello @Guillawme, hopefully, this is now fixed.

**Comment by jayeshbadwaik** [comment]
Yes, it is fixed now. Thanks a lot. :-)

**Comment by Guillawme** [comment]
Thank you!
