### ISSUE TITLE
Any chance of tweaking Minimo for Gatsby?

### ISSUE THREAD

**Issue by kevinctofel** [MunifTanjim/minimo#287]
I love the theme or I wouldn't be asking. ;) Using it on Hugo for my personal site but thinking about moving to Gatsby. I don't mind putting in the effort to give it a try and tweak for Gatsby use (I haven't even looked into what it would take yet) but before I started, wanted to ask.

Cheers!
kct

**Comment by MunifTanjim** [comment]
You can't really "tweak" it to make it work on Gatsby. Gatsby has a totally different theming system. So, you'll need to port the theme for Gatsby. And that'll be a whole lot of work.

I don't think I can manage the time to do it. But, Minimo is licensed under MIT License. So you are more than welcome to do whatever you want with it's source code. 😃
