### ISSUE TITLE
Site search

### ISSUE THREAD

**Issue by matrixik** [MunifTanjim/minimo#29]
I found nice and simple hack for searching site:
https://blog.philipphauer.de/moving-wordpress-hugo/#search

>Many Hugo users employ Google Custom Search. But it contains ads (in the free edition). That’s why I’m using a simple HTML form and redirect to Google Search but restrict the search to my site.

```html
<form role="search" method="get" action="https://www.google.com/search">
  <input type="search" placeholder="Search..." value="" name="q" title="Search for:">
  <input type="hidden" name="sitesearch" value="blog.philipphauer.de">
  <button type="submit" value="Search"/>
</form>
```

**Comment by matrixik** [comment]
And looks like that gohugo.io is using https://www.algolia.com

**Comment by MunifTanjim** [comment]
@matrixik Yes, there are various ways of implementing search in Hugo sites.

However, for sharing tips & tricks, [Hugo Discussion](https://discourse.gohugo.io) would be more a more suitable place. :slightly_smiling_face:
