### ISSUE TITLE
How to hide "date" field on pages/posts?

### ISSUE THREAD

**Issue by lelibreauquotidien** [MunifTanjim/minimo#292]
Hello !
All is a title :).

**Comment by MunifTanjim** [comment]
It's not clear what you meant at all. You need to elaborate.

**Comment by lelibreauquotidien** [comment]
Hello.
I would like to hide the publication date field on pages and articles.
I didn't find an option in config.toml.
Have a nice day.

**Comment by MunifTanjim** [comment]
You need to use the following custom CSS:

```css
.entry-meta .posted-on {
    display: none;
}
```

See #64 to know how to use custom CSS.

**Comment by lelibreauquotidien** [comment]
OK,thank you !
