### ISSUE TITLE
Author information page

### ISSUE THREAD

**Issue by troyane** [MunifTanjim/minimo#296]
Currently I feel like missing one thing -- how can I add authors personal page. For example as it is done here: https://hugomodo.github.io/authors/thom-bruce/

I'd like to put some information about author + pics + list of his articles. I thought that it is quite vital and popular requirement for any blog with few possible authors :)

@MunifTanjim could you point, please, what files should I tweak?

**Comment by MunifTanjim** [comment]
You can copy the **`/themes/minimo/layouts/_default/list.html`** to **`/layouts/taxonomy/author.html`** and then modify it to include whatever you want.

Reference Links:
- https://gohugo.io/templates/lookup-order/#examples-layout-lookup-for-term-pages

**Comment by troyane** [comment]
Thanks for pointing it out, @MunifTanjim.

For someone who will searching the same question, here is the steps required (at least it was enough for me):

1. Copy the `./themes/minimo/layouts/_default/list.html` to `./layouts/taxonomy/author.html` as it is.
2. Prepare folder for authors to be like: 

```
  |-author1
  |  |-_index.md
  |-author2
  |  |-_index.md
  |-_index.md
```

where top `_index.md` stands for a list of all available authors, and each author's `_index.md` is dedicated to particular author.
