### ISSUE TITLE
en.toml file not recognised

### ISSUE THREAD

**Issue by joejohnston1989** [MunifTanjim/minimo#3]
When running the run.exe I am receiving an error - 
Failed to load translation in file "en.toml": unsupported file extension .toml

Any ideas why?

**Comment by MunifTanjim** [comment]
What are you trying to do? I don't think there's any run.exe file related to Hugo.

Which Operating System are you on? And can you share the link for your site's repository?

**Comment by MunifTanjim** [comment]
Closed due to insufficient info. Will reopen if issue still persists.

**Comment by joejohnston1989** [comment]
Apologies. When I run hugo, it is telling me en.toml is not supported.

**Comment by MunifTanjim** [comment]
Try a fresh installation of minimo. If error still occurs provide the following information:

- Hugo version
- Operating System
- Your hugo config
- Complete error message

And if possible, share your site's repository.

**Comment by kenold** [comment]
I'm getting the same error:
- Hugo 0.18
- Windows 10
- Fresh Hugo install
```
PS C:\***\site> hugo server -w
ERROR: 2017/06/29 10:47:49 hugo.go:365: Current theme does not support Hugo version 0.18. Minimum version required is 0.2
Started building sites ...
ERROR: 2017/06/29 10:47:49 template.go:495: Failed to add template theme/partials/footer/copyright.html in path C:\***\site\themes\minimo\layouts\partials\footer\copyright.html: template: theme/partials/footer/copyright.html:6: function "now" not defined
ERROR: 2017/06/29 10:47:49 template.go:529: template: theme/partials/footer/copyright.html:6: function "now" not defined
Error: Error building site: Failed to load translations in file "en.toml": unsupported file extension .toml
```

**Comment by MunifTanjim** [comment]
@kenold are you sure that you have Hugo v0.24.1? Looks like, you have v0.18!

What's the output for `hugo version` command?

**Comment by kenold** [comment]
@MunifTanjim You're right. I was working on two different PCs and the one I'm currently one was still using v0.18. I updated Hugo to 0.24 and no more errors.

**Comment by MunifTanjim** [comment]
Cool. So, this issue is related to Hugo version. Currently Minimo needs atleast Hugo v0.20.

_And in future, it might even need a higher version._
