### ISSUE TITLE
Social menu not displayed in Chrome v87

### ISSUE THREAD

**Issue by dongzhuoer** [MunifTanjim/minimo#301]
https://minimo.netlify.app/

Chrome
![image](https://user-images.githubusercontent.com/15871952/103168080-3dc5b600-486b-11eb-800a-de313b9d2397.png)

Firefox
![image](https://user-images.githubusercontent.com/15871952/103168087-48804b00-486b-11eb-8a91-cbd6a58b2bc4.png)

**Comment by MunifTanjim** [comment]
You probably have some social button blocker extension on your Chrome.

**Comment by dongzhuoer** [comment]
I switch to incognito mode, and everything looks fine. Thank you so much!

**Comment by dongzhuoer** [comment]
I found that **Adblock Plus** extension is the casue, and unchecking the "Block social media icons tracking" button can solve the problem.
![image](https://user-images.githubusercontent.com/15871952/103203930-1507f400-4931-11eb-830d-41c4d2e0a6f3.png)
