### ISSUE TITLE
Thee does not work with latest hugo version.

### ISSUE THREAD

**Issue by chamindu** [MunifTanjim/minimo#303]
My website that uses this theme (https://github.com/chamindu/chamindu-website) does not work with the latest hugo version) ( v0.80.0-792EF0F4/extended) .  I tried with the example site bundled with the theme and it fails too the error message I get is.

Start building sites …
^[[AERROR 2021/01/05 18:44:18 render of "term" failed: execute of template failed: template: _default/list.html:1:3: executing "_default/list.html" at <partial "header" .>: error calling partial: execute of template failed: template: partials/header.html:19:14: executing "partials/header.html" at <partial "extras/widget_area" (dict "Widgets" $headerWidgets "Scope" .)>: error calling partial: execute of template failed: template: partials/extras/widget_area.html:7:8: executing "partials/extras/widget_area.html" at <partial (print "widgets/" .) $.Scope>: error calling partial: execute of template failed: template: partials/widgets/breadcrumbs.html:18:16: executing "breadcrumbs_add_parents" at <{{template "breadcrumbs_add_parents" (dict "Config" .Config "Page" $parent "Scratch" .Scratch)}}>: exceeded maximum template depth (100000)
ERROR 2021/01/05 18:44:18 render of "term" failed: execute of template failed: template: _default/list.html:1:3: executing "_default/list.html" at <partial "header" .>: error calling partial: execute of template failed: template: partials/header.html:19:14: executing "partials/header.html" at <partial "extras/widget_area" (dict "Widgets" $headerWidgets "Scope" .)>: error calling partial: execute of template failed: template: partials/extras/widget_area.html:7:8: executing "partials/extras/widget_area.html" at <partial (print "widgets/" .) $.Scope>: error calling partial: execute of template failed: template: partials/widgets/breadcrumbs.html:18:16: executing "breadcrumbs_add_parents" at <{{template "breadcrumbs_add_parents" (dict "Config" .Config "Page" $parent "Scratch" .Scratch)}}>: exceeded maximum template depth (100000)
ERROR 2021/01/05 18:44:18 render of "term" failed: execute of template failed: template: _default/list.html:1:3: executing "_default/list.html" at <partial "header" .>: error calling partial: execute of template failed: template: partials/header.html:19:14: executing "partials/header.html" at <partial "extras/widget_area" (dict "Widgets" $headerWidgets "Scope" .)>: error calling partial: execute of template failed: template: partials/extras/widget_area.html:7:8: executing "partials/extras/widget_area.html" at <partial (print "widgets/" .) $.Scope>: error calling partial: execute of template failed: template: partials/widgets/breadcrumbs.html:18:16: executing "breadcrumbs_add_parents" at <{{template "breadcrumbs_add_parents" (dict "Config" .Config "Page" $parent "Scratch" .Scratch)}}>: exceeded maximum template depth (100000)
ERROR 2021/01/05 18:44:18 render of "taxonomy" failed: execute of template failed: template: _default/terms.html:1:3: executing "_default/terms.html" at <partial "header" .>: error calling partial: execute of template failed: template: partials/header.html:19:14: executing "partials/header.html" at <partial "extras/widget_area" (dict "Widgets" $headerWidgets "Scope" .)>: error calling partial: execute of template failed: template: partials/extras/widget_area.html:7:8: executing "partials/extras/widget_area.html" at <partial (print "widgets/" .) $.Scope>: error calling partial: execute of template failed: template: partials/widgets/breadcrumbs.html:18:16: executing "breadcrumbs_add_parents" at <{{template "breadcrumbs_add_parents" (dict "Config" .Config "Page" $parent "Scratch" .Scratch)}}>: exceeded maximum template depth (100000)
Built in 54412 ms
Error: Error building site: failed to render pages: render of "taxonomy" failed: execute of template failed: template: taxonomy/author.terms.html:3:3: executing "taxonomy/author.terms.html" at <partial "header" .>: error calling partial: execute of template failed: template: partials/header.html:4:4: executing "partials/header.html" at <partial "head/head" .>: error calling partial: execute of template failed: template: partials/head/head.html:2:5: executing "partials/head/head.html" at <partial "head/meta" .>: error calling partial: execute of template failed: template: partials/head/meta.html:6:3: executing "partials/head/meta.html" at <partial "head/opengraph" .>: error calling partial: execute of template failed: template: partials/head/opengraph.html:1:38: executing "partials/head/opengraph.html" at <partial "data/title" .>: error calling partial: execute of template failed: template: partials/data/title:14:8: executing "partials/data/title" at <partial "data/author/displayName" .>: error calling partial: execute of template failed: template: partials/data/author/displayName:12:17: executing "partials/data/author/displayName" at <index $.Site.Data.authors ($.Scratch.Get "authorID")>: error calling index: value is nil; should be of type string

**Comment by MunifTanjim** [comment]
Are you using the latest minimo?

**Comment by j1mc** [comment]
I was able to get things to work with latest minimo and latest hugo (extended version, tho i'm not sure if that matters).

I do think it would be good to remove some of the "muniftanjim"-specific references from the example content, but things do work.

**Comment by Guillawme** [comment]
I just got the same error with Minimo (commit ba35b82) and Hugo 0.80.0:

```
Error building site:
  failed to render pages:
    render of "taxonomy" failed:
      execute of template failed:
        template: _default/terms.html:13:3:
          executing "_default/terms.html" at <partial "extras/taxonomy_cloud" (dict "Taxonomy" $taxonomy "Shuffle" $shuffle "Scope" .)>:
          error calling partial: "/Users/guillaume/gitlab/gaullier.org/themes/minimo/layouts/partials/extras/taxonomy_cloud.html:10:14":
      execute of template failed:
        template: partials/extras/taxonomy_cloud.html:10:14:
          executing "partials/extras/taxonomy_cloud.html" at <len $Data.Terms>:
          error calling len: reflect: call of reflect.Value.Type on zero Value
```

**Comment by Guillawme** [comment]
After some investigation, I found out that in my case the error was caused by a messed up directory structure under `content/tags` and `content/categories`. Moving these md files where Hugo expects them resolved my problem and my site now builds normally.

**Comment by chamindu** [comment]
> Are you using the latest minimo?

yes I am using the latest.

**Comment by j1mc** [comment]
For me, the trick was to initially set up my site by copying over content, config and data samples from the theme's 'exampleSite' directory and by following the install instructions. I do think the theme is working, and that this can be closed - even with the most current version of Hugo.

**Comment by AaronGullickson** [comment]
I am getting the same error when trying to serve this theme from a quickstart Hugo build:

```
Error: Error building site: failed to render pages: render of "taxonomyTerm" failed: execute of template failed: templat
e: taxonomy/author.terms.html:5:3: executing "taxonomy/author.terms.html" at <partial "header/header" .>: error calling
partial: execute of template failed: template: partials/header/header.html:15:14: executing "partials/header/header.html
" at <partial "data/author/displayName" .>: error calling partial: execute of template failed: template: partials/data/a
uthor/displayName:12:17: executing "partials/data/author/displayName" at <index $.Site.Data.authors ($.Scratch.Get "auth
orID")>: error calling index: index of untyped nil
```

Deleting the following lines from the `partials/data/author/displayName` allowed the site to be built, although I imagine it will mess up the author display name:

```
{{- $author := ( index $.Site.Data.authors ( $.Scratch.Get "authorID" ) ) -}}
{{- $i18nAuthor := ( index $author $lang ) -}}
{{- $name := ( or $i18nAuthor.name $author.name ) -}}
{{- $name.display -}}
```

**Comment by Rio517** [comment]
@AaronGullickson I ran into this as well, but it was due to using an older version of Hugo. I'm on Linux Mint and the latest version available via apt was v0.68.3. After installing v0.80, this issue was resolved.

**Comment by waseeld** [comment]
I am getting the same error when i trying to Hugo build:

```
Error: Error building site: failed to render pages: render of "taxonomyTerm" failed: execute of template failed: template: 
taxonomy/author.terms.html:5:3: executing "taxonomy/author.terms.html" at <partial "header/header" .>: error calling partial: 
execute of template failed: template: partials/header/header.html:15:14: executing "partials/header/header.html" at <partial "data/author/displayName" .>: 
error calling partial: "/home/waseel/was/busniss/Mothrey-blog/themes/minimo/layouts/partials
/data/author/displayName:13:21": execute of template failed: template: partials/data/author/displayName:13:21: executing 
"partials/data/author/displayName" at <index $author $lang>: error calling index: index of untyped nil
```

Some info :
❯ hugo version : v0.68.3/extended (Last version on apt)
❯ OS :  linux/amd64
❯ minimo version : 2.9.0

**Comment by MunifTanjim** [comment]
Minimum Hugo version required: 
https://github.com/MunifTanjim/minimo/blob/8a47ff3e3848f8d5a45ed7b6e235b34a6ae3e1b1/theme.toml#L42

**Comment by waseeld** [comment]
> Minimum Hugo version required:
> 
> https://github.com/MunifTanjim/minimo/blob/8a47ff3e3848f8d5a45ed7b6e235b34a6ae3e1b1/theme.toml#L42

oooh that is work thank you :+1: 
okay i install the last version from snap ..

My slution is :

```
sudo apt remove hugo

sudo snap install hugo

```
