### ISSUE TITLE
Sidebar support multiple "Taxonomy Cloud Widget"

### ISSUE THREAD

**Issue by dongzhuoer** [MunifTanjim/minimo#305]
Currently, `taxonomy_cloud.taxonomy` can only take one value. Would it be possible to support both "tags widget" and "categories widget" in the sidebar?

**Comment by MunifTanjim** [comment]
You can do this:
- Copy the [minimo/layouts/partials/widgets/taxonomy_cloud.html](https://github.com/MunifTanjim/minimo/blob/ba35b8250b991729f59bb0b10e73ccb0460b10ff/layouts/partials/widgets/taxonomy_cloud.html) file in your repository's `/layouts/partials/widgets/taxonomy_cloud_two.html` path.
- Replace `taxonomy_cloud` with `taxonomy_cloud_two` in that file.
- Add `taxonomy_cloud_two` to your sidebar's widget list in the `config.toml` file.

**Comment by j1mc** [comment]
Thanks for that tip here, @MunifTanjim. Like you suggest, I created a template ... but I also had to add a section on `/data/config/widgets.toml`, as well.  Here's how both looked:

```
{{- $defaultConfig := .Site.Data.config.default.widgets.taxonomy_cloud_categories -}}
{{- $configData := ( or .Site.Data.config.widgets.taxonomy_cloud_categories $defaultConfig ) -}}
{{- $lang := .Site.Language.Lang -}}
{{- $config := ( ( index $configData $lang ) | default $configData ) -}}

{{- $shuffle := ( $config.shuffle | default true ) -}}
{{- $taxonomy := ( $config.taxonomy | default "categories" ) -}}
{{- $taxonomyData := ( .Site.GetPage $taxonomy ).Data -}}
{{- $taxonomySingular := $taxonomyData.Singular -}}

<section class='widget widget-taxonomy_cloud sep-after'>
  <header>
    <h4 class='title widget-title'>
      {{- ( $config.title | default ( i18n $taxonomySingular 2 ) ) -}}
    </h4>
  </header>

  {{ partial "extras/taxonomy_cloud" ( dict "Taxonomy" $taxonomy "Shuffle" $shuffle "Scope" . ) }}

</section>
```

And then here's the related `/data/config/widgets.toml` info:

```# Taxonomy Cloud Widget config for Categories
[taxonomy_cloud_categories]
title = ""                            # default: Plural Name for `taxonomyCloud.taxonomy`
taxonomy = "categories"                     # default: "tags"
shuffle = true                        # default: true```

Thanks for your great work on this theme.

**Comment by dongzhuoer** [comment]
Your comments @MunifTanjim indeed works. Yet I need to point out one more thing -- especially for a HUGO novice -- `extras/taxonomy_cloud` should remain unchanged when replacing `taxonomy_cloud` with `taxonomy_cloud_two`.

By the way, have you considered add this tip somewhere in the documentation?
