### ISSUE TITLE
support/feat: Insert image without using cover

### ISSUE THREAD

**Issue by dannyloxavier** [MunifTanjim/minimo#336]
Hi!

Is it possible to use `![example](path/to/img.jpg)` to render images in pages and posts? (not only with `cover:` option)
I'm not having success and didn't find anything about in the minimo documentation. =/

**Comment by MunifTanjim** [comment]
Of course. That is markdown feature. The theme (in this case, minimo) has nothing to do with that.

Maybe you've got the path wrong? Can you show me an example repo where you tried that?

**Comment by dannyloxavier** [comment]
found the problem...
I'm using old .md files (migrating from another theme)
It was:
```
<center>
![example](path/to/img.jpg)
</center>
```
Removing the unnecessary HTML code solved the problem.
Sorry for my mistake. =/
And thank you for your response.
