### ISSUE TITLE
relative URLs to CSS, JS and logo broken since hugo post v0.100.2

### ISSUE THREAD

**Issue by berthubert** [MunifTanjim/minimo#337]
In this issue https://github.com/gohugoio/hugo/issues/9994 Hugo fixed a problem issue with baseURL and {{ $url | relURL }}
Sadly it appears that Minimo relied on the previous behaviour. Since updating to the latest Hugo, various files are no longer sourced from https://berthub.eu/articles/ but from https://berthub.eu/ straight - without the baseURL being used.
There is some useful discussion about this problem with another theme here: https://discourse.gohugo.io/t/solved-projectname-prefix-is-disappered-in-css-location-info-after-deploy-to-github-pages/40018
In there it is noted that the theme needs to adjust to the old and the new situation, which is sadly beyond my skills. 
Thank you for the wonderful theme, it makes me very happy!

**Comment by MunifTanjim** [comment]
Thanks for reporting this. This should be fixed with https://github.com/MunifTanjim/minimo/commit/b58c486f872a9ab74f9e22ea9a895ddea87921d9
