### ISSUE TITLE
Date format in li element is not configurable

### ISSUE THREAD

**Issue by matrixik** [MunifTanjim/minimo#34]
Hello,
Looks like date format in `li` element is not configurable. 
https://github.com/MunifTanjim/minimo/blob/master/layouts/_default/li.html#L7

On post pages I could change it with `dateFormat = "2006-01-02"`

**Comment by MunifTanjim** [comment]
It's already been discussed here: #24 & #28

**Comment by matrixik** [comment]
Oh, sorry, it's late here and I did not search for it. I will simply overwrite it and as ISO format is shorter (and more readable to not native speakers) so looks like it's should be fine with proper positioning.

**Comment by MunifTanjim** [comment]
On second thought, let me keep this issue open. I'll see if I can come up with a solution that can adjust to any length of date format. :slightly_smiling_face:

**Comment by MunifTanjim** [comment]
`listDateFormat` option added

**Comment by matrixik** [comment]
Working fine, thank you.
