### ISSUE TITLE
tags page in side bar menu?

### ISSUE THREAD

**Issue by jimpriest** [MunifTanjim/minimo#340]
Trying to convert my old blog from Pelican to Hugo...

I have everything working but instead of using the tags widget in the sidebar I just want a "Tags" link 

I added a /content/tags/_index.md

```
---
title: Tags
menu: 
    sidebar:
weight: 50
---
```

If I run hugo server -D locally I can visit  http://foo/tags  and get what I expect - a page which displays my taxonomy cloud.

However when I actually publish my site and deploy it - when I visit /tags/ I get the gopher and Page Not Found?

What am I missing :)

**Comment by MunifTanjim** [comment]
Are you using the same hugo version both locally and for deployment?

**Comment by jimpriest** [comment]
Yep they are identical:

```
local : hugo version
hugo v0.105.0-0e3b42b4a9bdeb4d866210819fc6ddcf51582ffa linux/amd64 BuildDate=2022-10-28T12:29:05Z VendorInfo=gohugoio

gitlab build server image: 
hugo v0.105.0-0e3b42b4a9bdeb4d866210819fc6ddcf51582ffa linux/amd64 BuildDate=2022-10-28T12:29:05Z VendorInfo=gohugoio
```

I've tried with a content/tags/ folder and _index.md,  without and tags folder,  and I also copied the /tags folder from the example site.

I'm toasting the contents of my website dir each deploy just to ensure there isn't anything cached, etc.  

My current config.toml:   https://gist.github.com/jimpriest/9d2ea1ea48fb47534b050a1a816b5de2

Reading the Hugo docs it seems like the /tags taxonomy is enabled by default and should just work so I'm confused as to why its not working :)

**Comment by jimpriest** [comment]
I found it - I was using --cvs-excludes in my rsync command one of the things this strips is "TAGS" LOL 

Lesson learned!
