### ISSUE TITLE
Text is automatically converted to emoji

### ISSUE THREAD

**Issue by hwdef** [MunifTanjim/minimo#345]
# Text:
![image](https://github.com/MunifTanjim/minimo/assets/13084946/e719a716-c306-4c21-8b84-1f479a25049d)

# output effect:
![image](https://github.com/MunifTanjim/minimo/assets/13084946/6d30817f-0490-4510-a569-19d97d87d1a1)

How do I keep it from being automatically converted?

**Comment by MunifTanjim** [comment]
Are you using this setting?

https://minimo.netlify.app/docs/emoji-support/

**Comment by hwdef** [comment]
Yes.
With this option turned off, I get the desired effect.
Thank you!!!

**Comment by hwdef** [comment]
@MunifTanjim 
By the way, can you open sponsor in github? I do not have account in buymeacoffee.

**Comment by MunifTanjim** [comment]
Hey...unfortunately, GitHub Sponsor is not yet available for my country. So right now I'm stuck with just Patreon or BuyMeACoffee.

But thanks for considering. 💜
