### ISSUE TITLE
Changing authors link

### ISSUE THREAD

**Issue by matrixik** [MunifTanjim/minimo#35]
One last thing and I'm going to sleep.

Could you tell me if it's possible to change authors URL link? Like it's possible with categories and tags.

I tried to change from `/authors/` to `/autorzy`
Test link: https://www.dobek.pro/2017/10/test/
My config: https://github.com/matrixik/dobek.pro/blob/master/config-minimo.toml
Test post source: https://github.com/matrixik/dobek.pro/blob/master/content/blog/test.md

I tried to change everything but looks like only `authors` add author near publish date but does not create https://www.dobek.pro/authors/matrixik page.

**Comment by MunifTanjim** [comment]
You will need to override the following files:
- `layouts/partials/entry/meta/author.html`
- `layouts/taxonomy/author.terms.html`

**Comment by matrixik** [comment]
OK, so it's hard-coded.
Overwriting them is working, thank you.
