### ISSUE TITLE
Setting defaultContentLanguage doesn't work

### ISSUE THREAD

**Issue by davidvidmar** [MunifTanjim/minimo#37]
I write my blog in Slovenian and when I tried setting my default language to "sl" and have it defined in [languages] section, it doesn't work. It can easily be checked with "hugo check" and that will always show "en".

Problem sits in example site's .toml file, where defaultContentLanguage is near the end of the file. 

According to the TOML spec, only maps/dictionaries can follow maps/dictionaries. You can confirm by doing a hugo config, but in your case you get the default, which is en.

As seen here: https://discourse.gohugo.io/t/solved-defaultcontentlanguage-does-not-seem-to-work/4135/10

**Comment by MunifTanjim** [comment]
@davidvidmar Thanks for the fix :smiley:

**Comment by davidvidmar** [comment]
Welcome! Thanks for great theme. Love it! I used it for my new blog at vidmar.net and also to learn Hugo/Go.
