### ISSUE TITLE
Question: Sort order of icon in social menu

### ISSUE THREAD

**Issue by davidvidmar** [MunifTanjim/minimo#39]
I cannot figure out how to do a custom sort of icons. Seems to me these are sorted alphabetically and not as specified in config.

**Comment by MunifTanjim** [comment]
It wasn't supported before. I just added it.

Docs: [Changing Social Menu Icons Order](https://minimo.netlify.com/docs/menus/#changing-social-menu-icons-order)

Update Minimo to the latest commit to get the feature.
