### ISSUE TITLE
Social icons not showing

### ISSUE THREAD

**Issue by leerobinson-wf** [MunifTanjim/minimo#41]
I'm not on the newest version and I see some changes have been made there. When I pull the newest version it works. However, there is a lot of other things changed that I don't necessarily want to be included with that. What specifically do I need to do to get the social icons working here? 

I tried retracing my steps through the commits and couldn't get it working. Here's my code - https://github.com/leerob/Portfolio/tree/master/themes/minimo

**Comment by MunifTanjim** [comment]
If you want to stick with the old version, here's the commit you'll want to checkout to: https://github.com/MunifTanjim/minimo/tree/2590a11b869b51709dca6a66c8ee8903c08575a7

But I'll suggest you to pull the latest stable version and follow these two guides to set everything up:

- **Install Minimo**: [Installation Guide](https://minimo.netlify.com/docs/installation)
- **Setup Authors**: [Authors Setup Guide](https://minimo.netlify.com/docs/authors)

The latest version contains various improvements over the old one.

**Comment by leerobinson-wf** [comment]
I checked out that commit and verify locally the icons are still not showing up. It looks like `social.html` is still using `author.social` in the config, which I have set. 

 I'm straying away from master because of CSS changes.

**Comment by MunifTanjim** [comment]
`author = "Lee Robinson"` under your `[params]` config is causing the problem. Why did you add that there?

**Comment by leerobinson-wf** [comment]
Thanks! Not sure why I did that... but that worked. Sorry for the confusion.
