### ISSUE TITLE
RSS link to blog posts on blog post page

### ISSUE THREAD

**Issue by matrixik** [MunifTanjim/minimo#50]
On post page (like <https://minimo.netlify.com/blog/minimo-v1-2-1-released/>) have RSS link to all blog posts.

So that all blog posts have RSS link in head:
`<link href="https://minimo.netlify.com/blog/index.xml" rel="alternate" type="application/rss+xml" title="Minimo" />`

Not sure if it's easily possible with Hugo.

**Comment by MunifTanjim** [comment]
That's not how `rel='alternate'` attribute works.

Quoting from [w3schools](https://www.w3schools.com/tags/att_link_rel.asp):
> **alternate** | Provides a link to an alternate version of the document.

So, what you are suggesting is not a standard thing to do.

**Comment by matrixik** [comment]
Hmmm, you are right. I just wanted to have what every Wordpress blog has working by default.

Like here:
https://en.blog.wordpress.com/2017/09/27/radcliffe-2/
`<link rel="alternate" type="application/rss+xml" title="WordPress.com Blog" href="https://en.blog.wordpress.com/feed/" />`

**Comment by matrixik** [comment]
For reference to get section RSS link (I'm still struggling to get proper condition in theme to add it only in `blog` section): 
`<link href='{{- .Section | absURL -}}{{- .Site.RSSLink | relURL -}}' rel="alternate" type="application/rss+xml" title="{{ .Site.Title }} Blog" />`

**Comment by matrixik** [comment]
OK, for adding RSS blog link to all pages:
1. Copy  `themes/minimo/layouts/partials/head/head.html` to `layouts/partials/head/head.html`):
2. After
```
  {{ if .RSSLink }}
    <link href="{{ .RSSLink }}" rel="alternate" type="application/rss+xml" title="{{ .Site.Title }}" />
  {{ end }}
```
add
```
  {{ with .Site.GetPage "section" "blog" }}
    <link href='{{- .Section | absURL -}}{{- .Site.RSSLink | relURL -}}' rel="alternate" type="application/rss+xml" title="{{ .Site.Title }} - Blog" />
  {{ end }}
```
Not sure how to not add two RSS links in example.com/blog but I can live with that.

**Comment by MunifTanjim** [comment]
@matrixik Have you tried [Hugo Discussion](https://discourse.gohugo.io/)? There are a lot of people who can help you with this kind of problems. And also, many more people with similar problem will be benefited from you solutions as the forum has more users.

:smiley:
