### ISSUE TITLE
Page with entire blog archive

### ISSUE THREAD

**Issue by matrixik** [MunifTanjim/minimo#52]
Hello,

Would you be interested in adding page that will contain entire blog archive?
I found this example: https://parsiya.net/blog/2016-02-14-archive-page-in-hugo/
And it's output looks like: https://parsiya.net/archive/
Other and simpler example could be: http://cheeaun.com/blog/archives/

I started to look into it because looks like https://github.com/gohugoio/hugo/issues/448 won't be implemented any time soon.
But I have no experience with CSS nor JS so not sure how to properly position and skin it so it's looks like rest of the site.

**Comment by MunifTanjim** [comment]
I've looked into it. So, here's the thing:

- For supporting a truly date based archive, the feature will have to be implemented within Hugo.

- But, if you just want page with all the posts you have created, just copy the **`/layouts/_default/list.html`** template to **`/layouts/page/archive.html`** and modify the following part:

```html
  <div class='list-container'>
    <ul class='list'>
      {{ range ( where .Site.Pages "Section" "ne" "page" ) }}
        {{ .Render "li" }}
      {{ end }}
    </ul>
  </div>
```
Then create a content file **`/content/page/archive.md`** with the following front-matter:

```yaml
---
title: Archive
layout: archive
---
```

---

But I don't think I'll add this to the theme repository for now.

**Comment by matrixik** [comment]
So it was simpler than I though. Thank you.

**Comment by matrixik** [comment]
Just for reference: https://randomgeekery.org/2016/04/17/yearly-post-archives-in-hugo/
