### ISSUE TITLE
404 page not rendered via `hugo serve`

### ISSUE THREAD

**Issue by inge4pres** [MunifTanjim/minimo#53]
Hi,

I am testing the theme, let me tell you it's really beautiful but the 404 page is not working for me when running `hugo serve --config minimo.toml`. 
I am leaving the default gopher image usage, so in the conf I have

```
[params.assets]
favicon = "favicon.ico"
gopher = "" # used in 404 template ( Generator: https://gopherize.me )
```

Any ideas?
Thank you

**Comment by inge4pres** [comment]
It works perfectly when pages are generated via `hugo --config ...`

**Comment by MunifTanjim** [comment]
When running site in localhost using `hugo serve` command, the 404 page is generally rendered at `http://localhost:1313/404.html`.

This is not an issue with the theme. It's normal hugo behavior.

**Comment by inge4pres** [comment]
Sorry, thought it was not :).
Did test it on a HTTP server and it works great. Thank for your time developing the theme
