### ISSUE TITLE
Alphabetical Tag Cloud

### ISSUE THREAD

**Issue by vonbrownie** [MunifTanjim/minimo#58]
Hello! I am setting up my first Hugo site using the Minimo theme and I am trying to get my tag cloud to display the tags in alphabetical order.

The relevant code (I believe) is `range .Data.Terms.Alphabetical` and is found in the theme’s `term_cloud.html` partial, but the terms are displayed in random order nonetheless. Trying `ByCount` as a test also has no effect. I notice the [example site's tag cloud](https://themes.gohugo.io/theme/minimo/tags) is also in random order.

Any idea what I need to change in this theme’s template to generate the tags in alphabetical order? Thanks for any help!

**Comment by MunifTanjim** [comment]
Update to the latest version and use the `noTermCloudShuffle` option in you `config.toml` file.

Anyway, the shuffling was done in the [`main.js`](https://github.com/MunifTanjim/minimo/blob/f6382644d7a7306422601422de46d70be4e7b01d/src/scripts/main.js#L8-L12) file. That's why changing `term_cloud.html` partial had no effect.

**Comment by vonbrownie** [comment]
@MunifTanjim I updated, made the necessary modifications, and now have a working alphabetical tag cloud. Thank you for adding the feature and for creating a great theme!

**Comment by vonbrownie** [comment]
@MunifTanjim I updated, made the necessary modifications, and now have a working alphabetical tag cloud. Thank you for adding the feature and for creating a great theme!

**Comment by vonbrownie** [comment]
@MunifTanjim I updated, made the necessary modifications, and now have a working alphabetical tag cloud. Thank you for adding the feature and for creating a great theme!

**Comment by vonbrownie** [comment]
@MunifTanjim I updated, made the necessary modifications, and now have a working alphabetical tag cloud. Thank you for adding the feature and for creating a great theme!

**Comment by vonbrownie** [comment]
@MunifTanjim I updated, made the necessary modifications, and now have a working alphabetical tag cloud. Thank you for adding the feature and for creating a great theme!

**Comment by vonbrownie** [comment]
@MunifTanjim I updated, made the necessary modifications, and now have a working alphabetical tag cloud. Thank you for adding the feature and for creating a great theme!
