### ISSUE TITLE
Disqus comments section appears on a page ("About")

### ISSUE THREAD

**Issue by thanosgatos** [MunifTanjim/minimo#59]
Hello, 

To my best understanding, by checking the archetype for page.md, as well as the comments.html file, the comments section should not appear on pages. Please, correct me if I'm wrong.

In any case, it does appear, even if it is just with the message "We were unable to load Disqus. If you are a moderator please see our troubleshooting guide." (http://www.thanosgatos.com/about/). That said, I would like to achieve two things:

1. Not have the comments show on the "About" page
2. Have the Disqus comments function properly

The repo is https://github.com/thanosgatos/thanosgatos.com.

Any help would be more than welcome.

**Comment by MunifTanjim** [comment]
Have you tried adding this in the frontmatter of your Aobut page?

```yaml
comments: false
```

**Comment by thanosgatos** [comment]
I thought that was inherited from minimo/archetypes/page.md. 

I have added it to the page's frontmatter, but that didn't change anything.

**Comment by thanosgatos** [comment]
Nevermind. My bad!

Your suggestion works perfectly fine! I did a typo, writing "flase", instead of "false". 

Thank you for your help. I am going to close this one.
