### ISSUE TITLE
 Contents table generator bug?

### ISSUE THREAD

**Issue by idevz** [MunifTanjim/minimo#63]
Does minimo support an contents table generator?

If I set a `toc = true` in the Front Matter, hugo will generator an contents table for me, But the style generated I didn't like so much.

And I found, forgot the `toc` option, If I add a six `#` and any character in my content, minimo will generator a minimo style contents table for me, Is this a bug?

### toc=true and Table of Contents (by hugo)
<img width="217" alt="screen shot 2017-12-05 at 11 10 37 am" src="https://user-images.githubusercontent.com/2113827/33588319-38a50e58-d9ad-11e7-9ef3-23044a7f0ef8.png">
<img width="483" alt="screen shot 2017-12-05 at 11 10 29 am" src="https://user-images.githubusercontent.com/2113827/33588332-42850d9c-d9ad-11e7-9e18-d6f1a3c06bb6.png">

### six `#` and minimo style
<img width="209" alt="screen shot 2017-12-05 at 11 11 22 am" src="https://user-images.githubusercontent.com/2113827/33588354-5d651e72-d9ad-11e7-825e-41ca21c0f95c.png">
<img width="501" alt="screen shot 2017-12-05 at 11 11 36 am" src="https://user-images.githubusercontent.com/2113827/33588357-61e459cc-d9ad-11e7-85ab-54c5db1eb724.png">

**Comment by MunifTanjim** [comment]
Minimo supports TableOfContents. The first screenshot is actually how it was supposed to be. If you don't like the style you will have to override the template files & scripts yourself. Here are the list of source files where you will find source code related to `toc` template: **`toc.html`**, **`main.js`**, **`_toc.scss`**.

About the second screenshot, that is not "minimo style" and was not meant to happen that way. It occurs when the first heading of the content is `h6` (i.e. the first heading of markdown content starts with `######`).
It's a bug, and it affects other themes too. You should report it on [gohugoio/hugo](https://github.com/gohugoio/hugo) repository as it's not specific to Minimo.

**Comment by idevz** [comment]
got it, thanks a lot @MunifTanjim 👍

**Comment by Fastidious** [comment]
@MunifTanjim slightly related to this, is there a way to have a `toc` that behaves more like the vanilla `toc` (that is, without the expanding icon, and animation, but just always present)?

**Comment by MunifTanjim** [comment]
@Fastidious Change the `<details>` & `<summary>` tags with `<div>` in the **`toc.html`** file.

**Comment by TimothyBramlett** [comment]
Will the table of contents be generated if you insert `toc: true` in a `_index.md` page?  I added that to my front matter but the TOC doesn't seem to be generating...

**Comment by MunifTanjim** [comment]
@TimothyBramlett 

`/layouts/partials/entry/toc.html` partial is only used for `single.html` layout.

https://github.com/MunifTanjim/minimo/blob/20035b88dc5fa5be8bf40625bbd4d881bc52da45/layouts/_default/single.html#L6

So, it won't work on `_index.md` pages. Those pages generally use [`list.html`](https://github.com/MunifTanjim/minimo/blob/master/layouts/_default/list.html) layout.

**Comment by TimothyBramlett** [comment]
It looks like changing `_index.md` to `index.md` made it use the `single.html` template but then it started adding the date of the content and so instead I just went back to `_index.md` but added `{{ partial "entry/toc" . }}` to the `index.html` in my theme folder.  So that will work for me.
