### ISSUE TITLE
How to use ' lastmod ' front matter in minimo

### ISSUE THREAD

**Issue by idevz** [MunifTanjim/minimo#65]
Does minimo support display lastmod? And how ?

**Comment by MunifTanjim** [comment]
Minimo currently only displays the `.Date` param. It's located in the [posted-on.html](https://github.com/MunifTanjim/minimo/blob/eb5a71ec0219092fb86458cd64b1ccc18211e96a/layouts/partials/entry/meta/posted-on.html) partial.

You can override that specific partial layout to extend it to show `.LastMod ` param.

**Comment by idevz** [comment]
Have any examples for this?
```html
  <time class='date' xdatetime='{{ .LastMod.Format "2006-01-02T15:04:05Z07:00" }}'>
     {{- .Lastmod.Format $dateFormat -}}
  </time>
```
this didn't work for me.

**Comment by MunifTanjim** [comment]
@idevz try this:

```go
{{- dateFormat $dateFormat .Params.Lastmod -}}
```

**Comment by idevz** [comment]
It's working for me @MunifTanjim ,thanks a lot :)

**Comment by raheems** [comment]
This is what my posted-on.html file looks like. But the date is not updating. Any help? Thanks.

```
{{- $dateFormat := ( .Site.Params.settings.dateFormat | default "2006, Jan 02" ) -}}
<span class='posted-on'>
  {{- partial "svg/icons" "calendar" -}}
  <span class='screen-reader-text'>{{ i18n "postedOn" }} </span>
  <time class='date' xdatetime='{{ .LastMod.Format "2006-01-02T15:04:05Z07:00" }}'>
    {{- dateFormat $dateFormat .Params.Lastmod -}}
 </time>
</span>
```

**Comment by MunifTanjim** [comment]
@raheems 

https://github.com/MunifTanjim/minimo/blob/9db19f947a2571801b8e03cb97c6b7fa91c90506/layouts/partials/entry/meta/posted-on.html#L5-L6

Override the [/layouts/partials/entry/meta/posted-on.html](https://github.com/MunifTanjim/minimo/blob/9db19f947a2571801b8e03cb97c6b7fa91c90506/layouts/partials/entry/meta/posted-on.html) file by replacing `.Date.Format` with `.Lastmod.Format`

That should work

**Comment by MunifTanjim** [comment]
@raheems

It should be something like: `{{ if not ( eq .Date .Lastmod ) }}Last updated{{ end }}`. I'm not sure though, will need to test it.

But I like the idea of showing last modification time in the article footer. Would you care to create a separate issue for that?
