### ISSUE TITLE
Stop a page from show on "recent posts"

### ISSUE THREAD

**Issue by Fastidious** [MunifTanjim/minimo#66]
My `content` directory has `page` directory (with an `about.md` inside, for example), `blog` directory (with the blog entries) and `error` directory (it has an `error404.md` page). That last one is showing under "Recent Posts." What can be done to stop that from happening?

**Comment by MunifTanjim** [comment]
What does `error404.md` do? You can put it in the `/conent/page/` directory and use `url` param in the front-matter to specify your desired url.

**Comment by Fastidious** [comment]
@MunifTanjim will try and post back. Thanks!

**Comment by Fastidious** [comment]
@MunifTanjim that worked! Thanks.
