### ISSUE TITLE
Recent Posts

### ISSUE THREAD

**Issue by Fastidious** [MunifTanjim/minimo#67]
Where is the configuration to change that string (Recent Posts) to something else? I also noticed that they are only five entries showing, is there a configuration somewhere to set a different amount of entries to show?

Thanks much!

**Comment by MunifTanjim** [comment]
As Minimo supports **i18n**, every string you see inside Minimo can be changed to whatever you like.
Just override the i18n file of your language in your site. For example if your site's language is English, create **`/i18n/en.toml`** in your site's root folder and override the default [en.toml](https://github.com/MunifTanjim/minimo/blob/master/i18n/en.toml).

**Comment by MunifTanjim** [comment]
Unfortunately at this moment the amount of recent posts (5) is hardcoded in this file: [recent_posts.html](https://github.com/MunifTanjim/minimo/blob/f6382644d7a7306422601422de46d70be4e7b01d/layouts/partials/home/recent_posts.html).

I'll add a configuration option for it.

**Comment by Fastidious** [comment]
@MunifTanjim this is most excellent. Thank you!
