### ISSUE TITLE
Link from single entry to blog entry/page

### ISSUE THREAD

**Issue by Fastidious** [MunifTanjim/minimo#68]
I hope you don't mind the, now four, issues I have entered. I am excited about `minimo`!

Would it be possible to link the date on a single entry, to its location on the `blog` list? For example, if you go to this post, [https://collantes.us/2015/08/29/jekyll-and-git/](https://collantes.us/2015/08/29/jekyll-and-git/), and click on the date, it will take you to its place on the archive list (archive list is equivalent to `minimo`'s multipaged `blog`).

I was able to do it, but it breaks on the multipage approach.

**Comment by MunifTanjim** [comment]
I don't think this will be possible with multipage archive on Hugo (currently).
But who knows, maybe I'm wrong :joy:
