### ISSUE TITLE
RSS template

### ISSUE THREAD

**Issue by Fastidious** [MunifTanjim/minimo#69]
Since I couldn't find the RSS template, I am assuming the theme is using Hugo's default, correct? It seems to be including the blog, and everything else (all pages) for me. No good.

**Comment by MunifTanjim** [comment]
Hugo's default RSS adheres to the [RSS 2.0 Specification](http://cyber.law.harvard.edu/rss/rss.html) and is sufficient for most use cases.

If you need a customized RSS feed, you'll need to modify it yourself.

Hugo's documentation about [RSS Templates](https://gohugo.io/templates/rss/) is a good place to start researching.

**Comment by Fastidious** [comment]
@MunifTanjim I tried, yet, I couldn't make it so only the content of a specific section shows on RSS. I have:

```
content/
        blog/
        pages/
```

And used:

```
{{ range first 45 (where .Data.Pages "Section" "blog") }}
```

On the RSS, and still things under `pages` show on the feed. I am about to disable feeds all together. :-(

**Comment by MunifTanjim** [comment]
You can conditionally include the RSSLink in the `<head>` (using something like this):

```golang
 {{ if and ( .RSSLink ( eq .Section "blog" ) ) }}
    <link href="{{ .RSSLink }}" rel="alternate" type="application/rss+xml" title="{{ .Site.Title }}" />
  {{ end }}
```

And delete the unwanted `.xml` rss feeds after generating the site with `hugo`.

**Comment by Fastidious** [comment]
That works is I go to `/blog/`, but doesn't when going to `/` (which still shows the unwanted entries). I do not manually generate the site, it happens upon commit (post-receive hook). So annoying! I will continue researching and trying to see if I can find a solution. If I do, I will come back to post it.

**Comment by Fastidious** [comment]
OK, I got it to work by removing the `date` on the pages I did not want to be shown on RSS. Since they are not `blog` entries, they really didn't need date/time. Yay!

**Comment by Fastidious** [comment]
Happy on how it is looking now: https://collantes.us/ :-)
