### ISSUE TITLE
Categories and Tags

### ISSUE THREAD

**Issue by Fastidious** [MunifTanjim/minimo#70]
Is it possible to add a *blur* (description), and extra text on the Categories, and Tags pages? For example, on https://collantes.us/blog/ I was able to add a *blur*, and some text before the entries are rendered. Same for https://collantes.us/.

Is it possible to do that on categories and tags? As their directories are created on build, I can't go before hand and add an `_index.md` file, right?

**Comment by MunifTanjim** [comment]
On the latest version (commit https://github.com/MunifTanjim/minimo/commit/854ba365f099ffec536024996a039311897b1650), it's possible. E.g. for adding content before the Tags list:

- Create a **`tags`** directory in your **`/content/`** folder
- Add an **`_index.md`** file
- Add your contents there

**Comment by Fastidious** [comment]
Lovely, thanks!
