### ISSUE TITLE
Not generating index.xml and index.html in /public

### ISSUE THREAD

**Issue by taraskaduk** [MunifTanjim/minimo#73]
I am using this theme via `blogdown` package in R. After the last update, the theme seems failing to generate an index file when serving the site. Other themes don't have this issue. 

I don't know much about web development, and not sure what other details should I provide... Please let me know.

**Comment by MunifTanjim** [comment]
@taraskaduk you closed this issue. Was it resolved?

**Comment by pantaraas** [comment]
@MunifTanjim I bet it was my own stupidity. I somehow solved it, but not sure how. 
I apologize for raising false flags.
