### ISSUE TITLE
Consider adding a tag cloud/list on the home page

### ISSUE THREAD

**Issue by jobanputra** [MunifTanjim/minimo#75]
Would you consider adding a minimalistic tag cloud/list on the home page?

**Comment by MunifTanjim** [comment]
Check [**Homepage Sections**](https://minimo.netlify.com/docs/homepage-sections/) docs

**params.settings.homepageSections** configuration option available from 70d5aab2e9c32e0405593ea85144165fa7c67918

**Comment by MunifTanjim** [comment]
@jobanputra You'll have to do a bit of manual work to make this work. Let me know if there's any problem.
