### ISSUE TITLE
Author's name ends up in <title>

### ISSUE THREAD

**Issue by druxstr** [MunifTanjim/minimo#76]
I've set up authors and now the author's name appears in my blog posts <title>.

Expected : 

`<title> Blog post title • Website name </title>` 

Happening :

`<title> Blog post title • Author's name </title>`

My /data/authors/myauthor.toml is empty except for 2 fields :

<pre>
id = "authorid"

[name]
display = "Author's name"
</pre>

The value of display ends up in the title (and in the search engine results).

I'm using Hugo 0.31.1 and an the latest Minimo.

Also, thank you for making Minimo :)

**Comment by MunifTanjim** [comment]
You will have to override the [**`/layouts/partial/data/title`**](https://github.com/MunifTanjim/minimo/blob/232db8c7a1d6ebbb166dc00d175f132a69afca9b/layouts/partials/data/title#L23) template file. Take a look at line 23.

**Guide**: [Override Template Files](https://gohugo.io/themes/customizing/#override-template-files)

**Comment by druxstr** [comment]
OK, I didn't get that this was by design. Thanks !
