### ISSUE TITLE
Unproper capitalization for two words tags

### ISSUE THREAD

**Issue by druxstr** [MunifTanjim/minimo#77]
Tags listed at the bottom of blog posts are automatically capitalized, 

but capitalization fails with two words tags. For instance \:

`tags = ["bat", "cat", "guinea pig"]`

Should display

> Bat, Cat, Guinea pig

But instead displays

> Bat, Cat, guinea pig

I'm using Hugo 0.31.1 and an the latest Minimo.

**Comment by MunifTanjim** [comment]
I believe, this inconsistency is from [gohugoio/hugo](https://github.com/gohugoio/hugo).

What you can do is one of the followings:

- Open an issue on the **hugo** project repository

- Set the tag as: `tags = ["Guinea Pig"]`

- Set the tag as: `tags = ["guinea pig"]` and create a file **`/content/tags/guinea-pig/_index.md`** with the frontmatter `title: Guinea Pig`

**Comment by Fastidious** [comment]
Question, @MunifTanjim, could it be possible to lower case all tags/categories instead?

**Comment by MunifTanjim** [comment]
@Fastidious, yes. Override [taxonomy-list template file](https://github.com/MunifTanjim/minimo/blob/3155157828901482ee0ff1cf84b9075ca667f95e/layouts/partials/entry/taxonomy-list.html#L13) and run [`lower`](https://gohugo.io/functions/lower/) function on `.Title`

**Comment by Fastidious** [comment]
@MunifTanjim so:

```
 {{- .Title | lower -}}
```

**Comment by MunifTanjim** [comment]
You mean the `/tags/` page?
This is the layout file: `/layouts/_default/terms.html`

**Comment by Fastidious** [comment]
@MunifTanjim it seems what I was looking for was on `/layouts/partials/header/header.html`. I wanted to change:

*Tags:* Sometag

to 

*Tags:* sometag

And the same for category. I have asked on Hugo forums before, but sometimes I have been told to contact the theme's author. I appreciate your help, will refrain from bothering any further. Thanks again.
