### ISSUE TITLE
help want: Could you support a view like small word in the picture

### ISSUE THREAD

**Issue by idevz** [MunifTanjim/minimo#78]
# Just like the small word in the picture.(in the red circle: sub-linearly)

--------------
![xxxx](https://user-images.githubusercontent.com/2113827/34824661-638d8260-f70a-11e7-9adc-76ce07468f8b.jpeg)

**Comment by MunifTanjim** [comment]
You'll need your own html markup and css to achieve that.

Something like this might work:

**HTML**:
```html
<span class="mtxt">
  Main Text Part
  <span class="stxt">
    Sub Text
  </span>
</span>
```

**CSS**:
```
span.mtxt {
  display: inline-block;
  position: relative;
  font-size: 18px;
}
span.stxt {
  position: absolute;
  font-size: 10px;
  top: 80%;
  left: 10%;
}
```

It depends on how and where you intend to use it.

But I don't think this is something that any Hugo Theme will support.

**Comment by idevz** [comment]
@MunifTanjim thanks a lot, ok, I don't think so too that Hugo Theme will support this. thanks all the same.:)
