### ISSUE TITLE
Feature request: Add custom css?

### ISSUE THREAD

**Issue by cyra** [MunifTanjim/minimo#85]
Add a custom css param perhaps? I would like to be able to change my fonts, scss is kinda hard to work around with, i only have knowledge with normal css 💃

**Comment by MunifTanjim** [comment]
Have you tried the [`params.assets.customCSS`](https://github.com/MunifTanjim/minimo/blob/d48945abe2f8142101cf01e3b9ddd1619841d28a/exampleSite/config.toml#L28) config option?

**Comment by cyra** [comment]
I did not see that. Sorry for that 😅 Thanks for leading me the way.
