### ISSUE TITLE
Feature request: tweet a post

### ISSUE THREAD

**Issue by karampok** [MunifTanjim/minimo#86]
Hi, very nice theme.
I was wondering if it possible to have way in order to directly tweet/facebook a post?

Thanks!

**Comment by HorribleGeek** [comment]
@karampok
Are you talking about Share buttons?

**Comment by MunifTanjim** [comment]
You can use something like this anywhere in the template: `https://www.facebook.com/sharer/sharer.php?u={{ .Permalink }}`

**Comment by karampok** [comment]
@HorribleGeek  yes I am talking about share buttons
@MunifTanjim  I will try to see how it looks

thx

**Comment by HorribleGeek** [comment]
@karampok use svg and link it to permalink.. Like @MunifTanjim showed above. 

It will look cool!

**Comment by karampok** [comment]
I have to admit I am not familiar with the field.
Could you provide me a snippet of how the svg entry will look like, and which file should I place it?

Thanks!

**Comment by HorribleGeek** [comment]
@karampok i would have showed a live example but i switched my theme.

Anyways here is a quick code that i wrote
````
<!DOCTYPE html>
<html>
<body><svg class='icon' viewbox='0 0 24 24' stroke-linecap='round' stroke-linejoin='round' stroke-width='2' aria-hidden='true'>


<a href="https://gw.coregossip.com"><path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z"/></a></svg>
</body>
</html>

````

The path d defines the image, for this example it is facebooks svg and it links to my site. You can use what @MunifTanjim showed above.

Just replace the link. For time being you create a file named xyz.html in your local system, paste this code and test it out!

You will find svg code for most of social images in minimo theme itself. 

[Minimo SVG Icons](https://github.com/MunifTanjim/minimo/blob/master/layouts/partials/svg/icons.html)

For a quick note: svg stands for scalable vector graphics, that means.it doesnt matter if you look at the image on a 4k screen or a mobile device, the quality will be se and size minimal.

Give me your repo link and i will implemet this feature with a pull request.


Things to do-
Get the svg code for social share you want to implement.

Find the link... For specific shares, facebooks example is shown above by @MunifTanjim

Implement in your html for site. 

Test it!

Tip: dont forget to add <svg> and </svg>

**Comment by MunifTanjim** [comment]
Further discussion can be held on [Hugo Discussion Forum](https://discourse.gohugo.io/)
