### ISSUE TITLE
Bold hyperlink for Blog

### ISSUE THREAD

**Issue by anfractuosity** [MunifTanjim/minimo#9]
Hi,

First of all, thanks for this wonderful theme!

I'm just a bit stuck, you can see on my instance of the theme at http://www.alewand.com/blog/
the 'blog' text doesn't become bold.

I defined it in config.toml:

```
[[menu.main]]
    name = "blog"
    weight = -10
    identifier = "blog"
    url = "/blog"
```

Cheers
Chris

**Comment by MunifTanjim** [comment]
If you want to add your site's internal pages in menu, do that by using the frontmatter of that page.

For adding `/blog` to the Main Menu. Create a file `/content/blog/_index.md` with the frontmatter:

```
---
title: Blog
menu: main
weight: -220
---
```

That should do it.

Use `config.toml` to add menu item when it's an external link (e.g. https://example.com).

You can always check the [Minimo Demo](https://minimo.netlify.com)'s [source](https://github.com/MunifTanjim/minimo/tree/master/exampleSite) to see how it's done.

**Comment by anfractuosity** [comment]
Thanks a lot for your fast reply!

That fixed it 👍 

I'll take a look at the demo source too now.
