### ISSUE TITLE
Sidebar looks ugly on Mobile - In request desktop site, when zooming in.

### ISSUE THREAD

**Issue by HorribleGeek** [MunifTanjim/minimo#91]
Probably no one does this but can we fix this by making the sidebar fixed, not dymanic.

<a href="https://imgur.com/a/u563E">Minimo - Hugo - Imgur</a>

The sidebar has a fixed position, I think some pixels off top and left. Can we make it as the normal area is?

Like, zooming in and seeing the sidebar like normal.I tried my best to explain this if you still are not able to then comment, maybe I'll fix this.

**Comment by matrixik** [comment]
I think you linked to wrong image.

**Comment by HorribleGeek** [comment]
My bad - https://imgur.com/a/u563E

**Comment by HorribleGeek** [comment]
@MunifTanjim I was doing that just to see how it will look in desktop.

If it works good when zooming in in desktop and other devices then there is no need to consider this because no one requests desktop site for viewing a webpage.

**Comment by MunifTanjim** [comment]
Maybe something's wrong with the Firefox mobile app. Try it with the Chrome mobile for taking a look at it. :slightly_smiling_face:
