### ISSUE TITLE
Overview all the archives

### ISSUE THREAD

**Issue by neighborhood999** [MunifTanjim/minimo#95]
Hi @MunifTanjim 

Thanks for you create elegant, simple Hugo theme.

Recently, I wanna migrate my blog from Hexo to Hugo, I have a question: How can I create **Archives** page for overview my all the posts like [this](https://neighborhood999.github.io/archives/), I think this can help some user for quick overview all the posts. Thanks!

Below is my folder structure:

```
.
├── archetypes
│   └── default.md
├── config.toml
├── content
│   ├── 2018
│   ├── _index.md
│   ├── about
│   ├── archives
│   └── tags
├── data
│   └── authors
├── layouts
│   └── _default
├── static
│   ├── post-cover
└── themes
    └── minimo
```

**Comment by MunifTanjim** [comment]
It's definitely doable. Are you familiar with Hugo templates?

What you need is something like this:

```golang
    {{ range ( where .Site.RegularPages "Type" "ne" "page" ).GroupByDate "2006" }}
      <h3>{{ .Key }}</h3>
      {{ range .Pages }}
        {{ .Render "li" }}
      {{ end }}
    {{ end }}
```

**Comment by neighborhood999** [comment]
I'm not familiar Hugo templates, sorry for waste your time help me this stupid question.
I will read Hugo related document and try it, Thank you @MunifTanjim ! Have a nice day.

**Comment by MunifTanjim** [comment]
@neighborhood999

Well, I just pushed the `archive` layout for Minimo. For using it, add

```
type: page
layout: archive
```

in your content's frontmatter.

**Comment by neighborhood999** [comment]
Thanks for your work!
