### ISSUE TITLE
Justify the text ?

### ISSUE THREAD

**Issue by Zilkos** [MunifTanjim/minimo#96]
Hi !

Thanks for your awesome work on this theme, I really like it ! I was wondering if it's possible to get a switch for justified text.
```
text-align: justify;
```
Like the toc option on content entry for exemple. Sort of `justify: true`
Justified text is more confortable to read (especially in my native language) :) Maybe I can add it locally to my stylesheet ? How can I do that ?

**Comment by MunifTanjim** [comment]
If you need every post to have `text-align: justify`:

- Create a file **`/static/css/custom.css`** in your repo's root directory.
- Add these css in that file:
  ```css
  .entry-content {
    text-align: justify;
  }
  ```
- Add this file to your **`config.toml`** file's [**`customCSS`**](https://github.com/MunifTanjim/minimo/blob/ad7c7decde18289f475f784c42698800d34dcb57/exampleSite/config.toml#L28) option under `[params.assets]`:
  ```toml
  customCSS = ["css/custom.css"]
  ```
- That's it. It's more convenient than adding Params in each content file.

If that satisfies your need, great!

But if you want to justify text in only specific contents, let me know. I'll add a `justified` parameter like you mentioned in the issue.

**Comment by Zilkos** [comment]
It's exactly what I need, I just tested and it's okay !

Thanks !
