### ISSUE TITLE
authors vs author

### ISSUE THREAD

**Issue by raheems** [MunifTanjim/minimo#98]
The theme uses author parameter as `authors`. Was there any particular reason for not using `author`? I am thinking of compatibility when switching between themes. Thanks.

**Comment by MunifTanjim** [comment]
Well, currently I don't think there are any standard way of defining author in Hugo. So, everybody kind of comes up with their own implementation. When I initially implemented author support in Minimo, I tried it in a couple of ways and for some reason (which I don't actually remember now :joy:) liked this one most.

If you switch to a theme that doesn't support `authors` param, you can quickly search and replace all the `authors: ` param with `author: `. It should be fairly easy.

Related link: **[Author Support documentation](https://minimo.netlify.com/docs/authors/)**

**Comment by raheems** [comment]
Thanks a lot.
