### ISSUE TITLE
Editing main menu elements

### ISSUE THREAD

**Issue by raheems** [MunifTanjim/minimo#99]
Sorry for asking too many questions--

I was able to add an element to the main menu by adding the following to the `config.toml` file.

```
 [[menu.main]]
 name = "Post"
 weight = -11
 identifier = "post"
 url = "/post/"
 ```
However, this adds the POST element in addition to the existing elements. 

How would I remove an existing element?

**Comment by raheems** [comment]
Never mind. I've figured it out :)

I've copied `_index.md` to the `post` folder and edited accordingly. 

It seems, markdown is pretty neat. I am liking it :)

**Comment by MunifTanjim** [comment]
Going through [Hugo Documentation](https://gohugo.io/documentation/) would help you with a lots of things when starting with it for the first time.

[Hugo Menus](https://gohugo.io/content-management/menus/)

**Comment by MunifTanjim** [comment]
@raheems by the way, you should also check [Hugo Discussion](https://discourse.gohugo.io/).
